### ISSUE TITLE
stuart_the_minion - Incorrect update of borrow & liquidity interest rates when postprocessing a flash loan

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#101]
stuart_the_minion

High

# Incorrect update of borrow & liquidity interest rates when postprocessing a flash loan

### Summary

When postprocessing a flash loan, the `FlashLoanLogic` provides wrong loan fee value to the interest rate strategy as a balance update that will cause highly incorrect calculation of liqiduity & borrow rate values.

### Root Cause

In [FlashLoanLogic.sol:L118](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/FlashLoanLogic.sol#L118) `amountPlusPremium` is wrongly provided instead of `_params.totalPremium`.

```solidity
  function _handleFlashLoanRepayment(
    DataTypes.ReserveData storage _reserve,
    DataTypes.ReserveSupplies storage _totalSupplies,
    DataTypes.FlashLoanRepaymentParams memory _params
  ) internal {
    ... ...

    _reserve.updateInterestRates(_totalSupplies, cache, _params.asset, IPool(_params.pool).getReserveFactor(), amountPlusPremium, 0, '', ''); // <-- @audit-issue

    ... ...
  }
```

### Internal pre-conditions

- A reserve should have some debt so that the protocol can update the borrow rate.

### Attack Path

A malicious actor just borrows a flash loan to destabilize the ecosystem of a reserve.

### Impact

After a flash loan, the balance change should be just a flash loan fee but the logic provides the entire loan repay as the balance change to update the interest rates.

Therefore excessively out-of-orbit interest rates will severely disrupt the normal deposit and borrowing operations.

### PoC

I added this test case to `PoolFlashLoanTests.t.sol`.
```solidity
  function test_simple_flashloan_underlyingbalance_poc() public {
    bytes memory emptyParams;
    MockFlashLoanSimpleReceiver mockFlashSimpleReceiver = new MockFlashLoanSimpleReceiver(pool);
    _generateFlashloanCondition();

    vm.prank(bob);
    pool.borrowSimple(address(tokenA), bob, 50 ether, 0);

    poolFactory.setFlashloanPremium(2);
    uint256 premium = poolFactory.flashLoanPremiumToProtocol();
    assertEq(premium, 2);

    DataTypes.ReserveSupplies memory reserveSuppliesData = pool.getTotalSupplyRaw(address(tokenA));
    console.log("underlyingBalance Before flash loan: ", reserveSuppliesData.underlyingBalance);
    console.log("Actual Balance Before flash loan: ", tokenA.balanceOf(address(pool)), "\n");

    vm.warp(block.timestamp + 1 hours);

    vm.startPrank(alice);

    vm.expectEmit(true, true, true, true);
    emit PoolEventsLib.FlashLoan(address(mockFlashSimpleReceiver), alice, address(tokenA), 1000 ether, (1000 ether * premium) / 10_000);
    emit Transfer(address(0), address(mockFlashSimpleReceiver), (1000 ether * premium) / 10_000);

    pool.flashLoanSimple(address(mockFlashSimpleReceiver), address(tokenA), 1000 ether, emptyParams);
    vm.stopPrank();

    reserveSuppliesData = pool.getTotalSupplyRaw(address(tokenA));
    console.log("underlyingBalance After flash loan: ", reserveSuppliesData.underlyingBalance);
    console.log("Actual Balance After flash loan: ", tokenA.balanceOf(address(pool)), "\n");

    DataTypes.ReserveData memory reserveData = pool.getReserveData(address(tokenA));
    console.log("Borrow Rate After flash loan: ", reserveData.borrowRate);
    console.log("Liquidity Rate After flash loan: ", reserveData.liquidityRate);
  }
```

Here are the logs after running `forge test --match-test test_simple_flashloan_underlyingbalance_poc -vv`.
```bash
Ran 1 test for test/forge/core/pool/PoolFlashLoanTests.t.sol:PoolFlashLoanTests
[PASS] test_simple_flashloan_underlyingbalance_poc() (gas: 1203761)
Logs:
  underlyingBalance Before flash loan:  1950000000000000000000
  Actual Balance Before flash loan:  1950000000000000000000

  underlyingBalance After flash loan:  2950200000000000000000 // Wrongly exceeded underlyingBalance
  Actual Balance After flash loan:  1950200000000000000000 

  Borrow Rate After flash loan:  3723033495027083612665660 // The correct value should be 7445322453155295630384002
  Liquidity Rate After flash loan:  93066569291342618100614 // The correct value should be 372191834611220613848101
```

### Mitigation

Just replace `amountPlusPremium` with `_params.totalPremium` from the issued line:

```diff
-   _reserve.updateInterestRates(_totalSupplies, cache, _params.asset, IPool(_params.pool).getReserveFactor(), amountPlusPremium, 0, '', '');
+   _reserve.updateInterestRates(_totalSupplies, cache, _params.asset, IPool(_params.pool).getReserveFactor(), _params.totalPremium, 0, '', '');
```

**Comment by DemoreXTess** [comment]
Escalate

I initially identified this issue during the audit, but later realized why totalPlusPremium is being used. [This](https://github.com/aave/aave-v3-core/blob/782f51917056a53a2c228701058a6c3fb233684a/contracts/protocol/libraries/logic/FlashLoanLogic.sol#L246C1-L252C7) is Aave’s original implementation for flashloan repayment and interest rate updates. While it may seem unusual at first glance, when we examine an example like [Aave’s DefaultInterestRateStrategy](https://github.com/aave/aave-v3-core/blob/782f51917056a53a2c228701058a6c3fb233684a/contracts/protocol/pool/DefaultReserveInterestRateStrategy.sol#L171C1-L174C31), it becomes clear that the implementation here is correct.

The interest rate strategy calculates total liquidity with the following lines:

```solidity
      vars.availableLiquidity =
        IERC20(params.reserve).balanceOf(params.aToken) +
        params.liquidityAdded -
        params.liquidityTaken;
```

Although we don’t have aToken here and instead use the collateral token, it doesn’t matter. The key point is that the flashloan amount has not yet been transferred back to the pool when updating the interest rate.

```solidity
// ZeroLend Implementation

  function _handleFlashLoanRepayment(
    DataTypes.ReserveData storage _reserve,
    DataTypes.ReserveSupplies storage _totalSupplies,
    DataTypes.FlashLoanRepaymentParams memory _params
  ) internal {
    uint256 amountPlusPremium = _params.amount + _params.totalPremium;

    DataTypes.ReserveCache memory cache = _reserve.cache(_totalSupplies);
    _reserve.updateState(_params.reserveFactor, cache);

    _reserve.accruedToTreasuryShares += _params.totalPremium.rayDiv(cache.nextLiquidityIndex).toUint128();

&>  _reserve.updateInterestRates(_totalSupplies, cache, _params.asset, IPool(_params.pool).getReserveFactor(), amountPlusPremium, 0, '', '');

&>  IERC20(_params.asset).safeTransferFrom(_params.receiverAddress, address(_params.pool), amountPlusPremium);

    emit PoolEventsLib.FlashLoan(_params.receiverAddress, msg.sender, _params.asset, _params.amount, _params.totalPremium);
  }
```
Essentially, if we update the interest rate using the totalPremium parameter (as report mitigation), the interest rate strategy calculates the rate as if the flashloan amount won't be sent back to the pool. This means the interest rate is updated as though the flashloan amount remains out of the pool. For this reason, the report and its duplicates are completely invalid.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I initially identified this issue during the audit, but later realized why totalPlusPremium is being used. [This](https://github.com/aave/aave-v3-core/blob/782f51917056a53a2c228701058a6c3fb233684a/contracts/protocol/libraries/logic/FlashLoanLogic.sol#L246C1-L252C7) is Aave’s original implementation for flashloan repayment and interest rate updates. While it may seem unusual at first glance, when we examine an example like [Aave’s DefaultInterestRateStrategy](https://github.com/aave/aave-v3-core/blob/782f51917056a53a2c228701058a6c3fb233684a/contracts/protocol/pool/DefaultReserveInterestRateStrategy.sol#L171C1-L174C31), it becomes clear that the implementation here is correct.
> 
> The interest rate strategy calculates total liquidity with the following lines:
> 
> ```solidity
>       vars.availableLiquidity =
>         IERC20(params.reserve).balanceOf(params.aToken) +
>         params.liquidityAdded -
>         params.liquidityTaken;
> ```
> 
> Although we don’t have aToken here and instead use the collateral token, it doesn’t matter. The key point is that the flashloan amount has not yet been transferred back to the pool when updating the interest rate.
> 
> ```solidity
> // ZeroLend Implementation
> 
>   function _handleFlashLoanRepayment(
>     DataTypes.ReserveData storage _reserve,
>     DataTypes.ReserveSupplies storage _totalSupplies,
>     DataTypes.FlashLoanRepaymentParams memory _params
>   ) internal {
>     uint256 amountPlusPremium = _params.amount + _params.totalPremium;
> 
>     DataTypes.ReserveCache memory cache = _reserve.cache(_totalSupplies);
>     _reserve.updateState(_params.reserveFactor, cache);
> 
>     _reserve.accruedToTreasuryShares += _params.totalPremium.rayDiv(cache.nextLiquidityIndex).toUint128();
> 
> &>  _reserve.updateInterestRates(_totalSupplies, cache, _params.asset, IPool(_params.pool).getReserveFactor(), amountPlusPremium, 0, '', '');
> 
> &>  IERC20(_params.asset).safeTransferFrom(_params.receiverAddress, address(_params.pool), amountPlusPremium);
> 
>     emit PoolEventsLib.FlashLoan(_params.receiverAddress, msg.sender, _params.asset, _params.amount, _params.totalPremium);
>   }
> ```
> Essentially, if we update the interest rate using the totalPremium parameter (as report mitigation), the interest rate strategy calculates the rate as if the flashloan amount won't be sent back to the pool. This means the interest rate is updated as though the flashloan amount remains out of the pool. For this reason, the report and its duplicates are completely invalid.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by royalsalute** [comment]
I agree with @DemoreXTess regarding the update of interest rates. However, the test case exploited the vulnerability of the incorrect update of underlying balances. There will exist significant discrepancies between underlying and actual balances, and the more flash-loaning gets active, the more disparity will be accumulated.

Anyway, the impact will depend on how importantly `underlyingBalance` is used.

Therefore, I don't think this issue and its duplicates are completely invalid.

And the mitigation would be two alternatives:
1. A user must transfer `amountPlusPremium` amount from the flash loan callback, and removes the following line from the `_handleFlashLoanRepayment()`:
```diff
-   IERC20(_params.asset).safeTransferFrom(_params.receiverAddress, address(_params.pool), amountPlusPremium);
```
2. Updating interest rates after transfer

**Comment by 0xjuaan** [comment]
@DemoreXTess's escalation shows that the interest rate update is actually done correctly.
The secondary impact of `underlyingBalance` being incorrect is true, but has 0 impact since that variable is never used anywhere else in the code, so the issue and duplicates cannot be more than low severity.

**Comment by DemoreXTess** [comment]
Yes exactly, thank you @0xjuaan. Underlying balance is not used anywhere in the code and this is why I didn't mention it. The impact is zero in here.

**Comment by Vulsight** [comment]
Theres also this impact to be considered:

1. The totalSupplies.underlyingBalance is a uint128 variable.

2. In extreme scenarios, attacker using large flash loans along with the regular flash loans of other users for a token with large number of decimals could cause the totalSupplies.underlyingBalance reach its near maximum value.

3. In this stage, any further call to updateInterestRates that require liquidity to be added for this particular token would revert due to overflow. Leading to pool insolvency.

**Comment by Weebad123** [comment]
@DemoreXTess @0xjuaan 
Have a look at one of the duplicates of this particular issue.  #237 talks about staleness of the liquidity after the flashloan is taken. The root cause of #237 is different from all the duplicated issues, and the vulnerability described by #237 is very apparent, as it fails to implement AAVEs logic detailedly during a flashloan request and not the repayment. 

https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/237

The recommended mitigation provided by https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/237 is to follow aave's logic during flashloan request , and not repayment. https://github.com/aave-dao/aave-v3-origin/blob/6948864fc7e74b2b29fadfe2007998992060f84b/src/core/contracts/protocol/libraries/logic/FlashLoanLogic.sol#L99-L103

Zerolend current implementation is not in line with AAVEs following the report in #237. 

I agree that the recommendation provided by the other issues with the exception of #237 is flawed just as you detailed. But the vulnerability itself is in the flashloan request. The flashloan is taken from the liquidity of the reserve, which means the reserve's liquidity should be decremented as done in Aave's codebase.

**Comment by DemoreXTess** [comment]
@Vulsight You're correct but we need to calculate when it can overflow in order to decide the severity. I will provide a calculation with really high usage rates in order to reach that number quickly. By the way, we need to use 18 decimal tokens at max in order to calculate it because the others will be out of scope.

I will use WETH which has 18 decimals. Let say we have 2.4B $ flash loanable liquidity in the pool. It makes 1_000_000 WETH. uint128.max is equal to 3.4028236692093846346337460743177e+38. This number has 39 decimals. Current average timestamp difference between blocks is 14 seconds. I want to ignore this seconds in order to make this calculation simple and I am assuming there will 14 flash loan requests each block ( By the way, this frequency is extremely high ). Technically, 1 flash loan per 1 second ( I ignored 14 seconds with that way ). Let say, all the flash loans are using whole liquidity, 1_000_000 ETH. 

Firstly, we need to substract the 18 decimals from uint128.max. 39 - 18 = 21 decimals. Now, if I can reach 21 decimals with 1_000_000 number, it means it's overflowed. I am ignoring some numbers in uint128.max ( it makes the situation fast ). My 21 decimals number is 3.4e+20. Let's divide by 1_000_000 in order to calculate the required seconds for overflow 3.4e+20 / 1e+6 = 3.4e+14. Okay I need 3.4e+14 seconds in order to overflow that number. It makes 10_781_329 years. I think everything is clear right now.

**Comment by cvetanovv** [comment]
I agree with the points raised by @0xjuaan  and @DemoreXTess. 

The interest rate update logic using `amountPlusPremium` is correct and follows `Aave` established method, ensuring that the interest rate calculation reflects the correct liquidity conditions during flash loans.

Additionally, as @0xjuaan highlighted, the `underlyingBalance` discrepancy has no practical impact since it isn't used.
The overflow concerns in #237 are also unrealistic, as @DemoreXTess demonstrated through calculations.

Planning to accept the escalation and invalidate the issue.

**Comment by Weebad123** [comment]
@cvetanovv  issue #237 does not mention overflow concerns. It talks about the wrong accounting that would result from the staleness of the liquidity of the underlying reserve, which is a valid impact. In #237, this could lead to wrong accounting of the total reserve's liquidity. During supply and withdrawal,  there's update to the totalSupplies.underlyingBalance of a particular reserve. Failure to update this value will result in wrong accounting. And besides, the provided `

> AAVE code https://github.com/aave-dao/aave-v3-origin/blob/6948864fc7e74b2b29fadfe2007998992060f84b/src/core/contracts/protocol/libraries/logic/FlashLoanLogic.sol#L99-L103

`
is a clear proof that, during the **FLASHLOAN REQUEST (and unlike the other issues, not in the handleRepayment function)** , the underlyingBalance of the reserve's supplies is updated by decrementing it with the flashloaned request amount. But this particular action that AAVE does is missing in Zerolend. This is the point in #237. 

This is the link to zerolend's code where the liquidity of the underlying reserve is indeed used during the interest rate update function. (It's updated when liquidity is being added (by incrementing) whereas it's updated when liquidity is also taken(by decrementing) . During a flashloan request, liquidity is being taken out of the reserve's supplies, which is why AAVE updates it during A FLASHLOAN REQUEST)
Check it out, and contrast Zerolend and AAVE. It will be observed that the update is missing in zerolend but is vividly present in AAVE.

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/ReserveLogic.sol#L176-L177

**Comment by cvetanovv** [comment]
@Weebad123 I understand what you mean. I think #237 should be duplicated with the wrong accounting of the `totalSupply` group(#375).

My previous decision to accept the escalation and invalidate the issue remains. #237 will be duplicated with #375.

**Comment by samuraii77** [comment]
@cvetanovv, I have also covered that scenario in #37 (my calculations are a bit wrong). If you decide to keep #237 valid, #37 is a duplicate. However, I don't see much in common between #237 and #375 for them to be duplicated, they have a completely different root cause, thus they should not be duplicated to 375.

**Comment by Weebad123** [comment]
@cvetanovv I don't understand why #237 should be duplicated with #375. They have different root causes. #375 and its duplicates all talk about an issue associated with the `executeMintToTreasury` function resulting in the last withdrawal reverting. 
However, issue #237 talks about an issue during the Flashloan Request as discussed above already. 
I think #237 should stand alone. And besides, fixing #375 does not eliminate the root cause pointed out by #237. Please, have a look at it again. 

@samuraii77 I think issue #37 is correctly categorised under the #101 group, which is to be rightly invalidated due to the points raised by @DemoreXTess . @samuraii77, #37 and the issue #101 and its groups all talk about issues with the `handleFlashloanRepayment`, which unfortunately is invalid per points raised by @DemoreXTess . This is because, the current implementation adopted by Zerolend is the correct way AAVE handles its flashloan repayment function. You can check the AAVE codebase on repayment in the links I've previously provided.

**Comment by samuraii77** [comment]
I already deleted my comment before your message, @Weebad123, you are right that my issue and yours have nothing in common.

EDIT: Actually it's the same issue but both are invalid.

**Comment by 0xjuaan** [comment]
Just a note @cvetanovv 

#237 is not a dupe of #375

#237 is invalid because it's impact is that `totalSupplies.underlyingBalance` is wrong after a flash loan, but that state variable is never used in the entire protocol. It's similar to many of the issues in this group.

**Comment by Weebad123** [comment]
@0xjuaan  When users supply assets or liquidity to a particular reserve on Zerolend, the `totalSupplies.underlyingBalance` is increased. 

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/SupplyLogic.sol#L69-L78



When users withdraw their liquidity, this same state variable is updated (decremented) to reflect the current liquidity of the reserve. 
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/SupplyLogic.sol#L125-L134


The purpose of the `totalSupplies.underlyingBalance` is to track the available liquidity of every reserve, an important aspect of Zerolend's operations. So per the provided code comments I've provided, your point that this state variable isn't used anywhere in the codebase is flawed. And besides, the impact I specified is wrong accounting of a liquidity reserve.

And besides, if your claims are true, I guess a battle-tested codebase as AAVE wouldn't have to update `totalSupplies.underlyingBalance ` either. However, 
this is not the case, as AAVE updates this state variable `totalSupplies.underlyingBalance ` **during a flashloan request, and not the repayment** ( all the other invalid issues you specified talked about repayment of flashloan) . 
 It's a valid issue. 
Please have a look at it again.

**Comment by 0xjuaan** [comment]
There is 0 impact of `totalSupplies.underlyingBalance` being incorrect so in Sherlock it can't be valid, please have a read of the criteria for issue validity.

**Comment by Weebad123** [comment]
@0xjuaan Have a look at an out-of-scope contract available in the Zerolend's codebase. It's crystal clear that Zerolend will use the value of `totalSupplies.underlyingBalance` as part of its config for every reserve available on Zerolend , per the UI helper contract shown below. 
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/periphery/ui-helpers/UIHelper.sol#L121

It is why it tracks the available liquidity of every reserve.  And besides, an update of such an important state variable is overlooked, and you're claiming it has zero impact? 
Then perhaps, you should argue that there is no need for the protocol to even track the available liquidity of a reserve.  


And besides, during borrow, the liquidity of the reserve (`totalSupplies.underlyingBalance`) is what is decremented. See  
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/BorrowLogic.sol#L88-L95


During loan repayment too, the liquidity of the reserve is what is incremented to reflect the current state of the available liquidity of each reserve.  See 
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/BorrowLogic.sol#L139-L148 


 It's crystal clear that wrong tracking of this state variable poses a protocol insolvency risk. 
Please have a look at it again. Thank you. 
@cvetanovv  It's over to you, Sir. I'll accept whatever your judgment will be.

**Comment by cvetanovv** [comment]
@trachevgeorgi 

If they increase the interest rate, won't everyone benefit?

What if a user or liquidation bot front-runs him and steals his collateral?

**Comment by cvetanovv** [comment]
I consulted Sherlock HoJ to make sure I was interpreting the rules correctly. 

In this case, @0xjuaan is right, and we don't have any impact. 

For the issue to be valid, the **impact must be in the in-scope contracts**. Thus, the contracts that are provided for the audit are "secure". 

Planning to accept the escalation and invalidate the issue.

**Comment by trachevgeorgi** [comment]
> I consulted Sherlock HoJ to make sure I was interpreting the rules correctly.
> 
> In this case, @0xjuaan is right, and we don't have any impact.
> 
> For the issue to be valid, the **impact must be in the in-scope contracts**. Thus, the contracts that are provided for the audit are "secure".
> 
> Planning to accept the escalation and invalidate the issue.

Well, the root of the issue is in the contracts in scope and no matter what the contracts out of scope are there will always be an impact to the contracts in scope. I have provided two possible scenarios, which are both impactful.

The issue is not in the out of scope contracts, nor are they impacted, only the type of impact is determined by them, which is really common to many different types of findings.

**Comment by Weebad123** [comment]
@cvetanovv @trachevgeorgi 

I provided an out-of-scope contract not to demonstrate that the impact is in an out-of-scope contract, but rather to ascertain that the incorrect handling of such a state variable is critical to Zerolend's operations. 

Despite totalSupplies.supplyShares tracking supply and repay amount whereas totalSupplies.debtShares tracking withdrawal and borrow amounts, the totalSupplies.underlyingBalance is what tracks both of these operations in real time including flashloaning. 

I'll have no more to say, Sir. 
Thank you for the clarification and your time.

**Comment by iamnmt** [comment]
@cvetanovv 

There is an impact in #482 which is not mentioned in #101

> Since ReserveSupplies.underlyingBalance has uint128 type, in case of a token with a high total supply, the pool which includes this token could be DoS on the supply and repay function on this token, because ReserveSupplies.underlyingBalance could be overflow.

Do you think this impact is sufficient for medium severity?

**Comment by DemoreXTess** [comment]
@iamnmt I proved it can't happen for million years. Check my calculations.

**Comment by iamnmt** [comment]
@DemoreXTess 

Yes I do see your comment. But I want to provide an argument that has not been brought up. 

If a token has a high total supply then the overflow could happen. A token with high total supply is a completely normal ERC20 token. If the total supply is less than uint128, and the bug is fixed then the protocol could integrate with the token normally. But due to this bug the supply and repayment functionalities could be DoS.

**Comment by DemoreXTess** [comment]
I made that calculation with 1 flash loan per 1 second and each flash loan has 1_000_000 supply (Excluding decimals ). Are you saying it's not high enough to simulate this @iamnmt ?

**Comment by Vulsight** [comment]
@DemoreXTess Thank you for your detailed calculation using WETH. While your analysis is correct for WETH, it's important to consider that not all tokens behave similarly, especially those with much larger supplies. Let's consider SHIB (Shiba Inu) as an example, using 1% of the supply for flash loans:
SHIB has a total supply of 589,735,030,408,323 tokens with 18 decimals. Let's run through a calculation with SHIB:

SHIB total supply: 589,735,030,408,323 * 10^18
Flash loan of 1% of the total supply: 5,897,350,304,083,230 * 10^15

Now, let's calculate how many such flash loans it would take to overflow uint128:
uint128 max value: 340,282,366,920,938,463,463,374,607,431,768,211,455
Number of flash loans to overflow:
340,282,366,920,938,463,463,374,607,431,768,211,455 / (5,897,350,304,083,230 * 10^15) ≈ 57,700,890
Assuming one flash loan per second:
Time to overflow: 57,700,890 seconds ≈ 667.8 days ≈ 1.83 years
This demonstrates that with a token like SHIB, which has a much larger supply than WETH, we could potentially see an overflow in less than two years under high usage conditions, even with just 1% of the supply being used for flash loans.
Moreover, SHIB isn't unique in this regard. There are many other tokens with large supplies, such as PEPE, FLOKI, BABYDOGE, and others. These "meme coins" often have supplies in the quadrillions or even quintillions, which could potentially lead to similar overflow scenarios.
It's crucial to consider these edge cases when designing smart contracts that interact with arbitrary ERC20 tokens. While your calculation for WETH shows a very long time to overflow, tokens with much larger supplies can present a real risk of overflow within realistic timeframes for long-running contracts.

**Comment by DemoreXTess** [comment]
@Vulsight 


Thank you for your calculations but you can't flash loan 1% supply of shiba. It's not a realistic scenario.

**Comment by cvetanovv** [comment]
@Weebad123 Can you show me exactly where the impact is from the wrong tracking of `totalSupplies.underlyingBalance`?

The variable is used in `updateInterestRates()`, which is called by `executeWithdraw()`, `executeRepay()`, `executeSupply()`, and other functions, but it is for informational purposes only. I don't see where it is used to have more than Low/Information severity.

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/ReserveLogic.sol#L176-L177

You gave an example with a contract that is out-of-scope(`UIHelper.sol`), but even there is used by the `view` function(`getPoolAssetConfig()`), which by default is Low severity.

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/periphery/ui-helpers/UIHelper.sol#L121

My previous decision to accept the escalation and invalidate the issue remains.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [DemoreXTess](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/101/#issuecomment-2392464635): accepted
