### ISSUE TITLE
000000 - Users can't withdraw all of their funds upon withdrawing ETH using the NFT position manager

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#119]
000000

Medium

# Users can't withdraw all of their funds upon withdrawing ETH using the NFT position manager

## Summary
Users can't withdraw all of their funds upon withdrawing ETH using the NFT position manager
## Vulnerability Detail
Users can withdraw ETH directly using `NFTPositionManager::withdrawETH()`. Upon withdrawing, we have the following line in the Pool contract:
```solidity
if (params.amount == type(uint256).max) params.amount = balance;
```
The goal of this line is for users to be able to provide all of their balance as it is pretty much impossible to do so otherwise due to the interest accrued based on `block.timestamp`. When using the NFT position manager, upon withdrawing the WETH, we have this line:
```solidity
weth.withdraw(params.amount);
```
The provided amount value was not changed in any way, shape or form, thus it would be `type(uint256).max` in the case explained above. This would obviously revert as neither the `WETH` contract has that amount of funds, nor the NFT position manager contract has access to such an amount of funds. As the funds grow with `block.timestamp` which is an impossible value to predict, upon the user trying to predict that value, he would either choose a lower value causing him to not withdraw all his funds or he would provide a bigger value causing a revert.
## Impact
Users can't withdraw all of their funds upon withdrawing ETH using the NFT position manager
## Code Snippet
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/positions/NFTPositionManager.sol#L105-L113
## Tool used

Manual Review

## Recommendation
Handle the case where the provided amount input is `type(uint256).max`

**Comment by samuraii77** [comment]
Firstly, the code linked by you is for the repay function while this issue is about the withdraw function. All other issues are wrongly duplicated to mine. Secondly, there is a similar line in the flow, particularly in `SupplyLogic::executeWithdraw()` which is being called upon the pool withdrawal:
```solidity
 if (params.amount == type(uint256).max) params.amount = balance;
```
However, the `params.amount` being changed here is based on the input in that function:
```solidity
 DataTypes.ExecuteWithdrawParams memory params
```
While the `params.amount` used in `NFTPositionManager::withdrawETH()` is based on this struct:
```solidity
AssetOperationParams memory params
```
Thus, the position manager will try to withdraw `type(uint256).max` of ETH from the WETH contract which is impossible.

**Comment by 0x3b33** [comment]
Escalate 
per the above comment

**Comment by sherlock-admin3** [comment]
> Escalate 
> per the above comment

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by sleepriverfish** [comment]
Include the specific code
```solidity
  function withdrawETH(AssetOperationParams memory params) external payable {
    params.asset = address(weth);
    address dest = params.target;
    params.target = address(this);
    _withdraw(params);
    weth.withdraw(params.amount);
    (bool ok,) = payable(dest).call{value: params.amount}('');
    if (!ok) revert NFTErrorsLib.SendETHFailed(params.amount);
  }


```

**Comment by cvetanovv** [comment]
What I wrote on one duplicate applies in full to this issue as well: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/264#issuecomment-2402753462

That a user does not withdraw all their funds because of constant change is not Medium severity. What remains is not lost and is only dust amount. This issue is no more than Low severity.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/119/#issuecomment-2390976147): rejected

**Comment by samuraii77** [comment]
@WangSecurity @cvetanovv, I think this issue should not be resolved yet as #264 is still without a final decision and they share a similar impact, I just didn't reply here as I thought you won't resolve it yet as 264 is still not.

**Comment by WangSecurity** [comment]
Oh, yeah, it was an oversight on my side. Anyway, if 264 in the end valid, this will also be validated. Sorry @0x3b33 for unnecessary worsening your escalation ratio, but it’s deprecated already though

**Comment by 0x3b33** [comment]
Hehe, no worries :D
