### ISSUE TITLE
Obsidian - Malicious pool deployer can use a malicious oracle contract to steal funds of vault depositors

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#234]
Obsidian

High

# Malicious pool deployer can use a malicious oracle contract to steal funds of vault depositors

### Summary

The malicious deployer will pass in their own custom `oracle` that is currently harmless BUT is upgradeable. Later once vault depositors have deposited funds into the pool, the malicious deployer will upgrade the `oracle` contract to return an extremely inflated price (in [`getAssetPrice`](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/PoolGetters.sol#L158-L163)) for a collateral asset (1 wei WETH = 100000e6 USDC)

Now the malicious deployer can supply 100 wei of WETH to borrow all of the vault's deposited funds because of the overvalued collateral

### Root Cause

Allowing the pool deployer to specify any `oracle`

### Attack Path

1. When the pool is initialised, the deployer passes in an upgradeable `oracle` contract
2. Vault users deposit 100000e6 USDC into the pool
3. the deployer upgrades their `oracle` contract to inflate the value of 100 wei of WETH to be much greater than the value of assets deposited by the vault
4. The deployer will supply 100 wei of WETH and borrow all of the vault's deposited funds because of the overvalued collateral

### Impact

All the funds deposited to the pool from the vault will be lost, so vault depositors lose their funds.

### Mitigation

Only allow protocol whitelisted oracle contracts to be set via the Pool configurator

**Comment by 0xSpearmint1** [comment]
Escalate

The README clearly states:
>There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.

This issue shows how a pool manager can easily steal funds from a vault, therefore it should be a valid high.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> The README clearly states:
> >There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.
> 
> This issue shows how a pool manager can easily steal funds from a vault, therefore it should be a valid high. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation.

In the readme, it is clearly written that the protocol is interested in issues where the pool manager can harm the vault manager and vice versa. 

This is exactly the situation described in this issue.

> There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.

Planning to accept the escalation and make this issue High.

**Comment by Nihavent** [comment]
I believe this can be at most medium but probably low. This is due to the highly unlikely pre condition of a SuperPool admin who is “expected to act rationally” to add a pool with an unknown/upgradable oracle. 
Unknown and upgradable oracles are suspicious to any rational actor. 
Given how easy it is to check an oracle address was deployed from a trusted source like Chainlink this is very easy to avoid.

**Comment by 0xjuaan** [comment]
Firstly, there are no docs that specify that the oracle smart contracts of a pool should be analysed by the vault curators for potential future bugs (due to upgradeability). We cannot assume that vault curators will analyse smart contracts for vulnerabilities. if so, any bugs in the Pool leading to attacks by pool managers on vaults would be invalid, since the vault curators could audit the contracts and find the bugs, and therefore "rationally" not supply to such pools. Again, the contest README shows that the sponsors are interested in issues that allow one party (actors who manage pools) to cause losses to the other (actors who manage vaults).

Secondly, regarding likelihood (even though likelihood is not a criteria in Sherlock rules)- if supplying to AAVE, the likelihood is low due to the governance mechanisms required in order to configure a pool. However, with permissionless pool deployment as in Zerolend, paired with permissionless vault creation to supply to pools, this issue is much more likely. For example, just a few days ago, a Morpho pool was [exploited for $230k](https://x.com/omeragoldberg/status/1845515855792136525), due to an incorrect oracle contract. Note that Morpho is a similar system to Zerolend, where anyone can deploy a pool permissionlessly.

**Comment by DemoreXTess** [comment]
I strongly believe that @cvetanovv you have mistaken here while understanding of README. README states that:

> Essentially we expect all permissioned actors to behave rationally.

> There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.

Those two statement is contradict based on your understanding but normally it's not. In here, it states that admin should be assumed to behave rationally but whenever any problem occurs in that pool due to an admin mistake, the vaults shouldn't be affected by this problem. 

Based on my understanding, this issue is invalid because it needs unrational admin behaviours here. I also believe the submission's mitigation is really great security feature for the permissionless pools such as ZeroLend but due to README we shouldn't accept it in Sherlock right now.

**Comment by cvetanovv** [comment]
@Nihavent @0xjuaan @DemoreXTess I admit the readme is written confusingly:

> Essentially we expect all permissioned actors to behave rationally.
> There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.

How I understand the rule:
- `Essentially, we expect all permissioned actors to behave rationally.` - Pool and vault managers must behave rationally in all cases, the only exception is when they can harm themselves.
- `If an action done by one party causes the other party to suffer losses we'd want to consider that.` - It is clearly written here that such issues are recognized as valid.

The impact is also High severity.

I also plan to duplicate it with #233 under the same concept rule: **Malicious pool deployer:**

> **Root cause groupings**
>
> Issues with the same conceptual mistake.
> - Example: different untrusted external admins can steal funds.


I planning on accepting the escalation of this issue to be High Severity and will duplicate it with #233

**Comment by 0xjuaan** [comment]
Hi @cvetanovv, I don't believe that this finding should be duplicated with 233. The root cause of this is that the oracles do not require a whitelist, while the root cause of that finding is that the interest rate contracts do not require a whitelist.

The fix for that finding does not fix this finding, so if this was not submitted it would not be fixed and the issue would still exist in the code. Because of that, it is not correct to duplicate this with the other finding.

This is very similar to the recent Perennial contest [here](https://audits.sherlock.xyz/contests/518?filter=results). The various findings in which the malicious market coordinator manipulates key values to cause harm are separate findings (not duplicated) because they have different root causes, and fixing one does not fix the others.

**Comment by Nihavent** [comment]
>” How I understand the rule:
>
>Essentially, we expect all permissioned actors to behave rationally. - Pool and vault managers must behave rationally in all cases, the only exception is when they can harm themselves.
>If an action done by one party causes the other party to suffer losses we'd want to consider that. >- It is clearly written here that such issues are recognized as valid.
>The impact is also High severity.”

I agree with your interpretation. 
One aspect of the vault manager acting rationally is to do some due diligence as to which pools they add to their vault. They will do so because their interests are to protect the deposits into their vault from malicious pool deployed. Ie. vault managers won’t just randomly add pools. 

By not checking the oracle address for a pool they’re adding, they’re being negligent to their pool depositors and are therefore not acting rationally with respect to their own interests. 

I believe this would be so negligent that it’s almost a mistake. Either way this is a significant pre-condition which is outside the control of the attacker which is why this shouldn’t be high severity. 

Even if the mistake happens, the malicious pool needs to be placed somewhere in the supply queue and wait to receive deposits before anyone notices that it has a suspicious oracle. The duration of this time delay is also outside of the control of the attacker.

**Comment by git-denial** [comment]
> Root Cause
Allowing the pool deployer to specify any oracle

This is design decision.

**Comment by Honour-d-dev** [comment]
i agree with @git-denial that this is a design decision, whitelisting oracles == whitelisting tokens, which takes away the permissionless nature of zerolend (i.e. allowing anyone to create a pool with any tokens).

Given the permissionless nature of zerolend and the fact that there are no trust assumptions between vault admin and pool admin , it's irrational for a vault admin to add any pool without doing their due diligence as they should be aware of the risks involved.

whitelisting oracles is not a good idea/fix as it goes against the core zerolend design choice

**Comment by cvetanovv** [comment]
This issue is a duplicate of #233, and it doesn't matter if I accept or reject the escalation because the payout won't change because #233 is on the same Watson.

> This is very similar to the recent Perennial contest [here](https://audits.sherlock.xyz/contests/518?filter=results). The various findings in which the malicious market coordinator manipulates key values to cause harm are separate findings (not duplicated) because they have different root causes, and fixing one does not fix the others.

I was Perennial's lead judge and actively participated in the discussion. The only reason they were separate is because it was about a malicious **internal** admin. 

Here, we are talking about **external** admin. And I explained it very well in my previous comment. 

My decision is to duplicate this issue with #233.

**Comment by 0xjuaan** [comment]
Hi @cvetanovv, please take a look at the exception written below the [rule](https://docs.sherlock.xyz/audits/real-time-judging/judging#ix.-duplication-rules) that you stated here:
> The exception to this would be if underlying code implementations OR impact OR the fixes are different, then they may be treated separately.

**Impact:** For this issue, the impact is that the attacker can manipulate prices to steal all the funds by borrowing it with insufficient collateral. For #233 the impact is different, the impact is that the vault's funds are stuck since any actions will revert. In fact, unlike this issue, #233 is reversible by internal admins since they can `setImplementation` for the pool, and add a function allowing them to reset the interest rate contract to a non-malicious one, to allow vaults to withdraw their funds from the pool.

**Underlying code implementations:** For this issue, it requires setting a malicious upgradeable oracle contract upon pool creation. On the other hand, for #233 as mentioned in the duplicates, a perfectly fine interest rate contract can be used. For the attack, a malicious one can simply be set at any time via the pool configurator, after pool creation.

Since the impacts are different, and the underlying code implementations are different, I believe that these issues are not duplicates, according to the sherlock rules.

**Comment by cvetanovv** [comment]
Even if the impact and the code are different, I duplicate them because the root cause is a malicious external admin, and I duplicate them under the rule for the same conceptual mistake.

Even the example in the documentation is given with such an issue.

**Root cause groupings**
If the following issues appear in multiple places, even in different contracts. In that case, they may be considered to have the same root cause.

 **Issues with the same conceptual mistake.**
 > Example: different untrusted external admins can steal funds.

My decision to duplicate this issue with #233 remains.

**Comment by 0xjuaan** [comment]
Hi @cvetanovv, the [rule](https://docs.sherlock.xyz/audits/real-time-judging/judging#ix.-duplication-rules) that you are referencing has an exception clearly stated at the end of it which you have not addressed. That exception applies to this issue, please have a look at it.

> The exception to this would be if underlying code implementations OR impact OR the fixes are different, then they may be treated separately.

cc @WangSecurity can you please clarify if the exception should be considered?

**Comment by cvetanovv** [comment]
@0xjuaan Explain to me how you interpret this duplication rule by the same conceptual mistake:

> Example: different untrusted external admins can steal funds.

**Comment by 0xjuaan** [comment]
@cvetanovv There are 2 parts to the rule. The first part, which is the one you keep referencing, states that issues with the same conceptual mistake should be duplicated.

The second part says that as an exception- if the impact OR underlying code implementation OR fixes are different, then the issues can be treated separately.

If we consider both parts of the rule together, the issue should not be duplicated (since the impact and underlying code implementation is different as I explained [here](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/234#issuecomment-2421190965)). I'm not sure why you are only considering the first part. 

By the way, the example you provided `Example: different untrusted external admins can steal funds.` only applies to this issue, not #233. The other issue is different because funds are not stolen, they are locked until a Zerolend admin upgrades the pool contract to change the interest rate contract, to unlock the funds.

**Comment by cvetanovv** [comment]
@0xjuaan After consulting with Sherlock, it became clear that the rule for external admins means admins that the protocol integrates with(for example, AAVE or Compound).

Therefore, the arguments you gave that this issue is similar to those in the Perennial contest are valid: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/234#issuecomment-2413414795

Planning to accept the escalation and make this issue solo High.

**Comment by Honour-d-dev** [comment]
@cvetanovv 

I still believe this issue is invalid for the following reasons:

As you stated here
>How I understand the rule:

> - Essentially, we expect all permissioned actors to behave rationally. - Pool and vault managers must behave rationally in all cases, the only exception is when they can harm themselves.
> - If an action done by one party causes the other party to suffer losses we'd want to consider that. - It is clearly written here that such issues are recognized as valid.

- All permissioned actors are expected to behave rationally, this includes vault admins. Given that adding a pool to a vault is an admin responsibility, The admin is expected to behave rationally and not add a pool with an unknown/untrusted oracle given the obvious security risks involved.
This is not claiming that the vault admin should audit the pool code as stated [here](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/234#issuecomment-2412822517) , there's no need for that because all zerolend pools use the same implementation. checking for unknown oracle however is a very basic thing.

- Protocol has the power to override any pools oracle or interest strategy.
As seen [here](https://github.com/zerolend/zerolend-one/blob/6b681f2a16be20cb2d43e544c164f913a8db1cb8/contracts/core/pool/Pool.sol#L150-L158) the factory configurator (a protocol admin) can change the oracle on any zerolend pool if it appears suspicious. I believe this feature exists for this exact reason.

- As i mentioned in a previous comment, this is a design decision, whitelisting oracles == whitelisting tokens, which makes it impossible to deploy a pool with any token (as is the intended design) due to missing oracle in whitelisted oracles

**Comment by 0xjuaan** [comment]
Regarding 1) It is completely rational for vault admins to allocate funds to a normal looking pool with a hidden vulnerability in the oracle, since identifying issues in code is not their role. As described in other issues, chainlink does not support every token so it won't be abnormal for custom oracle contracts to be used in pools. 

Regarding 2) This point is valid for ~~#234~~ #233 (since it is a DoS without fund loss and can be resolved once admins are alerted), but does not apply to this issue. The malicious pool admin can update the oracle and steal all the funds in a single transaction before an alert of any issue.

Regarding 3) There can be a system where price oracles are submitted for review by anyone, and accepted by trusted accounts if non-malicious. This alternative ensures that pools with any token can be made, but admins **cannot** cause the other party (vault users/managers) to suffer losses.

**Comment by Honour-d-dev** [comment]
@0xjuaan 

> Regarding 1) It is completely rational for vault admins to allocate funds to a normal looking pool with a hidden vulnerability in the oracle, since identifying issues in code is not their role. As described in other issues, chainlink does not support every token so it won't be abnormal for custom oracle contracts to be used in pools.

There're only 3 external(non-zerolend) contracts that pool admins can integrate to their zerolend pool 1) token 2) oracle 3) interest strategy. Chainlink is not the only known oracle, and it's very easy for a vault admin to avoid a pool if they don't know/trust the oracle or if it's upgradeable(which can be easily verified on etherscan for example), no code review is necessary for this.

> Regarding 2) This point is valid for https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/234 (since it is a DoS without fund loss and can be resolved once admins are alerted), but does not apply to this issue. The malicious pool admin can update the oracle and steal all the funds in a single transaction before an alert of any issue.

I believe you mean #233 (which should be invalid as the DoS is less than a week from sherlock rules @cvetanovv , unfortunately i missed it).

>Regarding 3) There can be a system where price oracles are submitted for review by anyone, and accepted by trusted accounts if non-malicious. This alternative ensures that pools with any token can be made, but admins cannot cause the other party (vault users/managers) to suffer losses.

This is assuming the existence of external systems, i think we can agree that introducing a form of governance for approving tokens in a **permissionless** system is a contradiction. Using the same logic ,there can be a system where vault admins can submit pools to be reviewed for malicious tokens/oracles before adding them.

**Comment by 0xjuaan** [comment]
> This is assuming the existence of external systems

I don't mean external systems, I just mean a function to `requestWhitelistOracle()` and another one to `acceptWhitelistOracle()`. Yes this requires protocol admins to accept the oracle, but prevents pool admins from causing vault users to suffer losses, which was specified in the README as valid. 

>  if it's upgradeable(which can be easily verified on etherscan for example)

It does not have to follow an upgradeability standard which etherscan is able to decipher. If you look at a chainlink price feed like [this one](https://lineascan.build/address/0x3c6Cd9Cc7c7a4c2Cf5a82734CD249D7D593354dA), it's not upgradeable, but the owner can still change the feed to any arbitrary price (changing the aggregator address). So the malicious contract can be deployed in an identical way, and there wouldn't be any way to know that the oracle is malicious.

Ultimately, not whitelisting oracles allows for malicious pool managers to steal funds from vault users, which was specified in the README as a concern. The suggested fix mitigates the issue.

**Comment by DemoreXTess** [comment]
@cvetanovv Can we reconsider this issue per @Honour-d-dev 's comment on #234

**Comment by Nihavent** [comment]
If vault admins are permissions actors and therefore we expect them to behave rationally.
However this rationality does not extend to requiring them to check the code of the pool they’re adding. 

Where does this leave [this issue](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/258) in which a vault admin adds a malicious pool which can steal funds?

- Both attacks have same root cause stemming from permissionless design of the protocol. 
- Both attacks have similar pre conditions: rational admin who isn’t perfect adds malicious pool (yes a pool with an unknown/upgradable oracle must be assumed to be malicious)
- Both attacks have similar fixes: whitelisting oracles and whitelisting pools deployed through the factory. 


In my view it’s an arbitrary position to take to say that the rational vault manager will not check the pools they’re add to ensure they’re safe. 
But even if we take that position, it’s more arbitrary to say that they will check the functions in the contract but not the oracle address.

**Comment by cvetanovv** [comment]
The pool deployer is not expected to act rationally and may act maliciously if it can harm the Vault. It is written in the readme, and because of that, my decision remains.

> There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.

My decision to accept the escalation remains.

**Comment by WangSecurity** [comment]
Result:
High
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xspearmint1](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/234/#issuecomment-2393911693): accepted

**Comment by elhajin** [comment]
🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲🥲 #322


![Screenshot from 2024-10-26 23-37-25](https://github.com/user-attachments/assets/b794bbd6-10c9-4ff2-8942-e56693a0b736)

**Comment by Joshuajee** [comment]
same applies here https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/233#issuecomment-2439982018

**Comment by elhajin** [comment]
@cvetanovv I think you misunderstand @Nihavent comment he means the vault owner should act rationally and don't add malicious pools.. the pool deployer can act maliciously as he wants since vault owners won't add their malicious pools if they act rationally . If vault owners don't act rationally this opens an arbitrary scenarios where a pool can be malicious and a vault owner adds them and they harm the vault.

**Comment by cvetanovv** [comment]
@elhajin Vault owner acts rationally and adds a pool that is not malicious. The pool owner sees this opportunity and updates the oracle to hurt the Vault owner.

Exactly this situation is written in the Readme: `There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.`

**Comment by Joshuajee** [comment]
@cvetanovv Oracles cannot be updated after the pool has been deployed, this vulnerability requires an upgradable oracle contract, every rational vault admin would see that this Oracle contract is not trusted or decentralized.

The attack requires that the vault admin will trust a pool that has a suspicious oracle.

**Comment by elhajin** [comment]
Admin who acts rationally will not invest in a pool that has an unknown oracle address (not a chainlink Oracle known address from their website) at least that seems rational to me 
 - it's easy to check that's the Oracle address  is legit and this will be probably displayed on ux (like flagging suspicious pools Like most of permissionless protocols do so vault owners don't invest in those pools) 
- and if you convince a vault owner to invest in your pool that have an unknown Oracle address that's basically  a phishing attack

> Vault owner acts rationally and adds a pool that is not maliciou

The pool need to be malicious in the first place .. and I think a pool that uses a malicious or upgradable  oracle address is a malicious pool(you can't change oracle so it has to be malicious in the deployment of the pool)

> Exactly this situation is written in the Readme: There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.

That should not be applied in this situation as we operate under the assumption that an owner should act rationally .. this issue requires a pool to be  malicious first and the  vault owner to add this malicious pool (which is irrational) as preconditions.. only in this case one party can cause the other party to suffer losses

**Comment by elhajin** [comment]
> Exactly this situation is written in the Readme: There are two set of actors. Actors who manage pools and actors who mange vaults. If an action done by one party causes the other party to suffer losses we'd want to consider that.

That should not be applied in this situation as we operate under the assumption that an owner should act rationally .. this issue requires a pool to be  malicious first and the  vault owner to add this malicious pool (which is irrational) as preconditions.. only in this case one party can cause the other party to suffer losses

**Comment by Nihavent** [comment]
I agree it’s a mistake by a permissioned actor to add a malicious pool with an unknown oracle address. 

At best this is an extensive pre condition which means this issue cannot be high. At worst this is a mistake which makes this issue invalid. 

My [comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/234#issuecomment-2429386955) also pointed out that if you rule this as valid then the linked issue should probably be duped with this. That Watson probably didn’t escalate because they accepted the lead judge’s decision that rational actors would never add a malicious pool.

**Comment by cvetanovv** [comment]
@Joshuajee @elhajin @Nihavent I understand that there is some conflict in the readme. There's no way the vault and pool managers are acting rationally and trying to hurt each other.

That the Oracle should be malicious in the beginning is a serious precondition. You are right about that. If the pool admin convinces the vault admin to use his oracle, which is an unknown/not famous oracle, it is a phishing attack. So my argument that the pool admin can upgrade the oracle is invalid because the vault admin is trusted to do his own checking on the oracle. 

For these reasons, I agree with you and will invalidate the issue.

**Comment by DemoreXTess** [comment]
@cvetanovv 

Then what about #233 ? It's exactly same submission the only difference it's about the interest rate strategy. Vault admin is trusted again and he needs to do his own checks on the strategy. 

For instance, the default interest rate strategy implementation of [AAVE](https://github.com/aave/aave-v3-core/blob/master/contracts/protocol/pool/DefaultReserveInterestRateStrategy.sol) is not using upgradeable structure and it doesn't use any set function for the global parameters. All the variables are defined at constructor which is totally safe for the protocol. I believe vault admin should follow this pattern while checking the strategy. 

This situation makes #233 invalid too.

**Comment by 0xjuaan** [comment]
@cvetanovv 

While the README says that permissioned actors are assumed to be rational, I don't think it's irrational for vault owners to supply to such a pool.

> Admin who acts rationally will not invest in a pool that has an unknown oracle address (not a chainlink Oracle known address from their website) 

1. The above statement is wrong, because for many tokens, chainlink oracles are not available on Linea (SOL, BNB, etc) and the next best option would be to make a custom oracle that pulls data from Pyth. These tokens will be used readily, so its not uncommon for a non-chainlink oracle to be needed in Zerolend. Hence, it is definitely rational to supply to a pool with a non-chainlink oracle since that is the only way to use such tokens.

2. If such a non-chainlink oracle was malicious, it can be hidden in a way that only security researchers can find it, I don't think it's fair to assume that vault owners can identify whether an oracle has a code vulnerability or not. Hence, it is a rational action to deposit into a malicious pool since there is no sign of any mistake.

3. Technically, there doesn't even need to be a vulnerability in the oracle. [Here](https://etherscan.io/address/0x4F01b76391A05d32B20FA2d05dD5963eE8db20E6) is an oracle used by [AAVE](https://app.aave.com/reserve-overview/?underlyingAsset=0xdc035d45d973e3ec169d2276ddab16f1e407384f&marketName=proto_mainnet_v3). The owner can call `setPriceCap()` to a price that is 1 wei above the current price, and when the price goes up, only `priceCap` will be returned from the oracle, allowing bad debt due to incorrect price. It's completely rational for vault owners to deposit into a pool of an **AAVE fork** which uses the **same oracle as AAVE**, deployed by the owner of the pool just like it's done in AAVE.

The README makes it clear that "If an action done by one party causes the other party to suffer losses we'd want to consider that.", and I have shown above why it's not irrational for vault depositors to supply to such a pool where a malicious pool owner can cause losses to a vault. Hence, the issue is valid.

**Comment by elhajin** [comment]
It's not necessarily chainlink that was just an example of a trusted oracle.. zeroland can whitelist some trusted oracle for all supported tokens (and its done off-chain) and vault owners will check against them before investing in any pool (not only malicious/unknown Oracles but all pools that have suspicious config should be flagged as spam on the front-end) 

- again we are talking about a honeypot scam here ..you need to convince/trick a vault owner to invest in a pool that has a hidden vulnerability but seems legit

**Comment by 0xjuaan** [comment]
> zeroland can whitelist some trusted oracle for all supported tokens (and its done off-chain)

This suggestion is a potential mitigation but it was not documented in the README. My message above explains why the issue is valid based on the README. 

> again we are talking about a honeypot scam here ..you need to convince/trick a vault owner to invest in a pool that has a hidden vulnerability but seems legit

In my 3rd point I showed that there doesn't even need to be a hidden vulnerability in the oracle.

**Comment by elhajin** [comment]
by vulnerability in the context of this issue I mean an oracle contracts that allows malicious actions..and an oracle that has a function  allows an owner to set the price cap to manipulate the price is a malicious oracle

At least that what I think

**Comment by iamnmt** [comment]
> The owner can call setPriceCap() to a price that is 1 wei above the current price, and when the price goes up, only priceCap will be returned from the oracle, allowing bad debt due to incorrect price. 

Shouldn't this oracle owner's action, not a pool owner action. And the oracle owner is trusted by default.

**Comment by cvetanovv** [comment]
Based on the README, the Vault admin is trusted to choose the Oracle properly because he is trusted. 

The only exception is when vault/pool admin can hurt each other. But there is a serious precondition for this to happen. A trusted admin must choose a malicious oracle. 

My previous decision remains: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/234#issuecomment-2442390839
