### ISSUE TITLE
Obsidian - A malicious user can re-allocate vault funds into a pool that is about to experience bad debt to cause significant loss for the vault

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#282]
Obsidian

High

# A malicious user can re-allocate vault funds into a pool that is about to experience bad debt to cause significant loss for the vault

### Summary

An attacker can use flash loans to re-allocate the funds of any vault into whichever pools they choose, this is best described in a set of steps.

Assume a vault deposits into pools A, B and C. Assume each pool has a cap of 60 ETH. The deposit queue is [A,B,C]. The withdraw queue is [A,B,C]. Note that all these numbers and orders are 100% arbitrary, the attack can be performed for any variation or caps/order.

Currently the allocations are as follows:

Pool A has 20 ETH deposited
Pool B has 20 ETH deposited
Pool C has 20 ETH deposited

Here is how the attacker can re-allocate all the funds into Pool C:

1. Attacker takes a flash loan of 120 ETH
2. Attacker [deposits](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/vaults/CuratedVault.sol#L322) 40 ETH into the vault, this will fill the cap for Pool A
3. Attacker deposits 40 ETH into the vault, this will fill the cap for Pool B
4. Attacker deposits 40 ETH into the vault, this will fill the cap for Pool C
5. Attacker withdraws 120 ETH, this will pull 60 from pool A and 60 from pool B
6. Attacker repays the 120 ETH flash loan (no fees since it was from balancer/maker)

Here is the allocation after the attack:

Pool A has 0 ETH deposited
Pool B has 0 ETH deposited
Pool C has 60 ETH deposited

The issue occurs when a pool is about to be in bad debt, an attacker can re-allocate all the vault's funds into the pool that will experience bad debt to cause a severe loss to the depositors.

### Root Cause

Anybody can use flash loans to arbitrarily reallocate vault allocations.

### Internal pre-conditions

Any pool supplied by vault is about to experience bad debt

### Attack Path

1. Attacker is observing the mempool looking for any pool that is deposited to from a vault, that has accumulated bad debt BUT not realised it yet 
2. Attacker re-allocates the vault’s funds into the bad debt pool using flash loans
3. When the bad debt is realised the vault depositors will experience a huge loss

### Impact

Vault depositors experience a severe loss since their funds were re allocated into a pool that experienced bad debt

Another point to note is that bad debt is not socialised in the protocol, this makes the impact even more severe if other pool suppliers withdraw first leaving the vault depositors with nothing

**Comment by iamnmt** [comment]
Escalate

This is a known issue

> Please list any known issues and explicitly state the acceptable risks for each known issue.
> See HAL-18 (page 34) on https://github.com/zerolend/audits/blob/main/halborn/Zerolend-One%20Audit.pdf

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is a known issue
> 
> > Please list any known issues and explicitly state the acceptable risks for each known issue.
> > See HAL-18 (page 34) on https://github.com/zerolend/audits/blob/main/halborn/Zerolend-One%20Audit.pdf

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation that this is a known issue from the previous audit of the Zerolend protocol (_7.11 (HAL-18) POTENTIAL TO SKEW LIQUIDITY ALLOCATION_).

Planning to accept the escalation and invalidate the issue.

**Comment by 0xjuaan** [comment]
Hi @cvetanovv please consider this:

The known issue has the impact of "potentially leading to underfunded pools and distorted market dynamics"

This submission shows that any user can reallocate funds of a vault bypassing the intentions of the risk curators, to cause significant loss to the vault depositors. At no cost, attackers can essentially use the vault’s liquidity as exit liquidity, so that other users can withdraw their funds from the pool and all the bad debt is effectively paid by the vault suppliers. 

The impact shown in the past audit is known, but the impact given in this issue is severe and cannot be considered a known issue.

**Comment by cvetanovv** [comment]
@0xjuaan This is the same issue as `HAL-18` from the previous audit. 

The readme states that the issues from the previous audit are not valid for this audit.

This issue can't be valid because of a different impact. It would be unfair to the other participants who read the previous audit, saw this issue, and decided not to write a report about this vulnerability.

My decision to accept the escalation remains.

**Comment by 0xjuaan** [comment]
I still think that just because this issue makes use of the same 'attack knob' of reallocating funds as the known issue, it cannot be written off as a known issue. It uses the same 'attack knob' to achieve a completely different outcome in a different context.

But I will respect the judging decision.

**Comment by cvetanovv** [comment]
Yes, my early decision remains, and that is that this is a known issue and, therefore invalid.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamnmt](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/282/#issuecomment-2391242876): accepted
