### ISSUE TITLE
hyh - CuratedVault cannot remove pool's allowances

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#333]
hyh

Medium

# CuratedVault cannot remove pool's allowances

### Summary

Lack of allowance removal enables rogue pools to steal `asset()` balance of the Vault, i.e. there is no pool integration defense mechanics, infinite allowances are permanent once set

### Root Cause

There are infinite approval setups on supply queue update and on supply allocation, while there is no allowance removal at all:

[CuratedVault.sol#L267-L268](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVault.sol#L267-L268) and [CuratedVault.sol#L177-L189](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVault.sol#L177-L189)

```solidity
  function setSupplyQueue(IPool[] calldata newSupplyQueue) external onlyAllocator {
    uint256 length = newSupplyQueue.length;

    if (length > MAX_QUEUE_LENGTH) revert CuratedErrorsLib.MaxQueueLengthExceeded();

    for (uint256 i; i < length; ++i) {
>>    IERC20(asset()).forceApprove(address(newSupplyQueue[i]), type(uint256).max);
      if (config[newSupplyQueue[i]].cap == 0) revert CuratedErrorsLib.UnauthorizedMarket(newSupplyQueue[i]);
    }

    supplyQueue = newSupplyQueue;
    emit CuratedEventsLib.SetSupplyQueue(_msgSender(), newSupplyQueue);
  }
```

There are no guarantees that all pools have the implementation provided in the current snapshot, CuratedVault only requires that these contracts follow `IPool` interface

### Internal pre-conditions

Pool contract is added to the Vault's `supplyQueue` or allocated during `reallocate`. Vault's `asset()` balance isn't empty

### External pre-conditions

Pool contract is jeopardized, so it can be utilized to use the allowance directly anyhow on attacker's benefit

### Attack Path

After supply queue addition or supply allocation to the pool's contract it is attacked, then permanent allowance is used to steal Vault's balance

### Impact

Vault's `asset()` balance can be fully stolen

### PoC

Not needed, it's a direct use of token allowance

### Mitigation

Consider resetting it to zero when pool's cap is reduced to zero, e.g.:

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVault.sol#L148-L155

```diff
  function submitCap(IPool pool, uint256 newSupplyCap) external onlyCuratorRole {
    if (pendingCap[pool].validAt != 0) revert CuratedErrorsLib.AlreadyPending();
    if (config[pool].removableAt != 0) revert CuratedErrorsLib.PendingRemoval();
    uint256 supplyCap = config[pool].cap;
    if (newSupplyCap == supplyCap) revert CuratedErrorsLib.AlreadySet();

    if (newSupplyCap < supplyCap) {
      _setCap(pool, newSupplyCap.toUint184());
+     if (newSupplyCap == 0) IERC20(asset()).forceApprove(address(pool), 0);
```

Also, to unify the logic and reduce overhead, consider moving `IERC20(asset()).forceApprove(address(pool), type(uint256).max)` operations to the moment when pool's cap is increased, e.g. to `acceptCap()`:

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVault.sol#L306-L309

```diff
  function acceptCap(IPool pool) external afterTimelock(pendingCap[pool].validAt) {
    // Safe "unchecked" cast because pendingCap <= type(uint184).max.
    _setCap(pool, uint184(pendingCap[pool].value));
+   IERC20(asset()).forceApprove(address(pool), type(uint256).max);
  }
```

**Comment by zarkk01** [comment]
Escalate

Escalate on the above comment of @dmitriia .

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Escalate on the above comment of @dmitriia .
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I believe this issue is Low severity.

The described scenario relies on a pool being compromised after it has already been integrated into the CuratedVault. The issue is real if the pool later becomes compromised. 

We don't have an issue at the moment. This falls into the future integration issue category, and the Readme states that the protocol is not interested about such issues.

> Should potential issues, like broken assumptions about function behavior, be reported if they could pose risks in future integrations, even if they might not be an issue in the context of the scope? If yes, can you elaborate on properties/invariants that should hold?
> - No

Planning to reject the escalation and leave the issue as is.

**Comment by dmitriia** [comment]
Pool being compromised is a prerequisite here, but any future integrations are not required. The issue is about an already integrated pool becoming compromised and having unremovable access to Vault's balance.

**Comment by cvetanovv** [comment]
@dmitriia, I think you are right here. It is not right to put this issue in the category of potential integration issues.

This issue shows how an already integrated pool is becoming compromised, and its permission cannot be removed.

Moreover, the readme states that the protocol is interested in issues where pools and vault actors can harm each other.

I am planning to accept the escalation and make this issue Medium.

**Comment by 0xjuaan** [comment]
The only way for this issue to be exploited is for the pool to have a different implementation to the actual Zerolend pools (since these approvals cannot be stolen via real zerolend pools)

This means that a vault admin must set a pool which is not does not use Zerolend's pool contract.

The root cause is that `PoolFactory.isPool()` is not checked in the vault when setting a pool.

This means that this should be duplicated with #239

**Comment by dmitriia** [comment]
@cvetanovv Thank you for the analysis.

@0xjuaan We cannot prove that `approvals cannot be stolen via real zerolend pools`, the absense of such issues in this and other reviews is not sufficient. Re grouping I think these issues require malicious actor, while this one doesn't. Also, these issues don't mention allowances at all, while this one focused on  allowance management. The only common feature is that pools aren't controlled enough, but for this issue it is not a prerequisite, we still can discuss allowances for particular zerolend pool implementation. The absense of pool control is a probability increasing factor only here, I think it's not sufficient for duping.

**Comment by 0xjuaan** [comment]
Hi @dmitriia, If a pool somehow because malicious (which can only happen if its not an official zerolend pool), the main risk is that all the funds stored in that pool can be stolen by simply transferring them out. The secondary, much smaller risk is that the approved funds from the vault (which only holds funds transiently) can be stolen. Please correct me if I'm wrong. 

If the above analysis is true, and if this is a valid issue, then #239 should be valid since they have the same precondition of malicious pool, but #239 mentions the primary impact rather than the secondary impact.

I'll leave the duplication decision to @cvetanovv but I am just stating the relationship between this issue and #239 since I did not escalate #239.

**Comment by Honour-d-dev** [comment]
i agree with @0xjuaan , as i mentioned during the judging, the current zerolend pool implementation does not have code to exploit this approvals (hence why no POC is available).

This issue is relying on future implementations/integrations as @cvetanovv correctly mentioned earlier or vault admin adding a non-zerolend pool , both of which are OOS.

This issue should be a low severity.

**Comment by dmitriia** [comment]
Hi @0xjuaan, If non ZeroLend pool is added and then becomes broken, for this review matter the pool's issues are OOS, but Vault balance access is not. Re duplication in addition to different focus as described above, as I understand, at this stage it is more about rejecting or accepting the escalation.

@Honour-d-dev `Curator` and `Allocator` can add any `IPool` compliant market right now, not being limited to ZeroLend implementation. This limitation your referencing to is not stated or implied anywhere, i.e. Vault by itself is universal and can accept different pools. This way there is no future integration requirement for the issue. Also, pool addition can be non-malicious by itself, so malicious `Curator` and `Allocator` are not required either, it is enough for them to have different interests, e.g. they might want to add non ZeroLend implementation in order to maximize Vault’s return or diversify it, so it becomes more appealing to depositors.

Since there are no blocked requirements it should be in scope as Vault contract is. As for severity, the impact is direct fund stealing, while cumulative requirements are achievable and fall under `requires certain external conditions or specific states` of Medium severity [definition](https://docs.sherlock.xyz/audits/real-time-judging/judging#v.-how-to-identify-a-medium-issue).

**Comment by cvetanovv** [comment]
The root of the issue is that once a pool is added, it gives infinite allowances. Then, under certain circumstances, that allowance may need to be removed, but that cannot happen. This is not mentioned in #239. 

The impact is also sufficient for Medium severity. There is a loss of funds, but this can only happen under certain circumstances.

My previous decision to accept the escalation remains.

**Comment by 0xSpearmint** [comment]
@cvetanovv The vault never holds any assets so the allowance cannot actually steal any funds since all of the vault's assets are deposited into pools.

**Comment by dmitriia** [comment]
Vault can legitimately hold funds, which are supposed to be managed by `skimRecipient` (CuratedVault.sol L312-317). The funds can be sourced from various pools, for example paying out reward tokens on withdrawals (which is a common practice).

I.e. the vault is made to be general, which makes probable for it to have value on the balance, which is not supposed to be free for all (it is not a router like design where every next user can utilize leftovers from previous operations), but rather supposed to be managed manually.

**Comment by Honour-d-dev** [comment]
>  The funds can be sourced from various pools, for example paying out reward tokens on withdrawals

There is no functionality in the current implementation though, currently vaults don't hold assets

**Comment by cvetanovv** [comment]
I would agree with @0xSpearmint and @Honour-d-dev. Right now, we don't have any impact because Vault doesn't hold any funds. 

Even if this Vault is given infinite allowances, it has no way at this stage to exploit it in a malicious way.

My decision is to reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [zarkk01](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/333/#issuecomment-2391035436): rejected
