### ISSUE TITLE
A2-security - Incorrect Calculation of Collateral to Seize in Liquidation

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#403]
A2-security

Medium

# Incorrect Calculation of Collateral to Seize in Liquidation

## Summary
The function `_burnCollateralTokens` calls `collateralReserve.updateIndex()` after the amount of collateral to seize is calculated in `_calculateAvailableCollateralToLiquidate()`. This order of operations results in an incorrect collateral valuation, as the updated index is not used in the calculation, leading to a potential undervaluation of collateral and an incorrect collateral amount being seized.

## Vulnerability Detail
The issue lies in the following sequence of calls in the `executeLiquidationCall`:
1. `_calculateAvailableCollateralToLiquidate` is invoked which uses the amount of collateral to seize is calculated. (There is a bug here that we discussed in another report in which the shares are not converted to assets)

2. `collateralReserve.updateIndex` is called after the available collateral is calculated in `_burnCollateralTokens`.

Here is an example of the problem:

```solidity
//@audit-issue amount of collateral to seize is calculated here, before the state for the seized reserved is updated.
    (vars.actualCollateralToLiquidate, vars.actualDebtToLiquidate, vars.liquidationProtocolFeeAmount) =
    _calculateAvailableCollateralToLiquidate(
      collateralReserve,
      vars.debtReserveCache,
      vars.actualDebtToLiquidate,
      vars.userCollateralBalance,
      vars.liquidationBonus,
      IPool(params.pool).getAssetPrice(params.collateralAsset),
      IPool(params.pool).getAssetPrice(params.debtAsset),
      IPool(params.pool).factory().liquidationProtocolFeePercentage()
    );

    if (vars.userDebt == vars.actualDebtToLiquidate) {
      userConfig.setBorrowing(debtReserve.id, false);
    }

    // If the collateral being liquidated is equal to the user balance,
    // we set the currency as not being used as collateral anymore
    if (vars.actualCollateralToLiquidate + vars.liquidationProtocolFeeAmount == vars.userCollateralBalance) {
      userConfig.setUsingAsCollateral(collateralReserve.id, false);
      emit PoolEventsLib.ReserveUsedAsCollateralDisabled(params.collateralAsset, params.position);
    }

    _repayDebtTokens(params, vars, balances[params.debtAsset], totalSupplies[params.debtAsset]);

    debtReserve.updateInterestRates(
      totalSupplies[params.debtAsset],
      vars.debtReserveCache,
      params.debtAsset,
      IPool(params.pool).getReserveFactor(),
      vars.actualDebtToLiquidate,
      0,
      '',
      ''
    );
@audit-issue the seized reserve state is updated for the first time in the end in `_burnCollateralTokens()`. After the liquidity calculations are already calculated.
@>>    _burnCollateralTokens(
      collateralReserve, params, vars, balances[params.collateralAsset][params.position], totalSupplies[params.collateralAsset]
    );
```
The reserve state is only updated there
```solidity
  function _burnCollateralTokens(
    DataTypes.ReserveData storage collateralReserve,
    DataTypes.ExecuteLiquidationCallParams memory params,
    LiquidationCallLocalVars memory vars,
    DataTypes.PositionBalance storage balances,
    DataTypes.ReserveSupplies storage totalSupplies
  ) internal {
    DataTypes.ReserveCache memory collateralReserveCache = collateralReserve.cache(totalSupplies);
@>>    collateralReserve.updateState(params.reserveFactor, collateralReserveCache);
```
In order to have a correct calculations of the seized assets we need to update state at the start of the function, as we need an updated state to calculate the amount of collateral to seize in `_calculateAvailableCollateralToLiquidate()`
## Impact
This bug causes the liquidation process to seize less collateral than intended, thereby not reflecting the accurate debt coverage. This may lead to a lower system stability as the seized collateral may be undervalued, and the remaining debt may not be adequately covered. This discrepancy affects the protocol's financial integrity and the users who might benefit unfairly from being liquidated with less collateral seized.
## Code Snippet
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L139C1-L176C7
## Tool used

Manual Review

## Recommendation
To mitigate this issue, update the state and accrue the interest rates  in `_calculateAvailableCollateralToLiquidate()`
```diff
  function _calculateAvailableCollateralToLiquidate(
    DataTypes.ReserveData storage collateralReserve,
    DataTypes.ReserveCache memory debtReserveCache,
    uint256 debtToCover,
    uint256 userCollateralBalance,
    uint256 liquidationBonus,
    uint256 collateralPrice,
    uint256 debtAssetPrice,
    uint256 liquidationProtocolFeePercentage
  ) internal view returns (uint256, uint256, uint256) {
    AvailableCollateralToLiquidateLocalVars memory vars;

    vars.collateralPrice = collateralPrice; // oracle.getAssetPrice(collateralAsset);
    vars.debtAssetPrice = debtAssetPrice; // oracle.getAssetPrice(debtAsset);

+    DataTypes.ReserveCache memory collateralReserveCache = collateralReserve.cache(totalSupplies);
+    collateralReserve.updateState(params.reserveFactor, collateralReserveCache);
```

**Comment by elhajin** [comment]
This is a different issue from #401; this one is about how, in the liquidation function, we use the outdated liquidity index of the collateral reserve to be seized to calculate the `availableCollateralToLiquidate` because we don't update the state for the `collateralReserve` before calculating liquidity here:

```js
_calculateAvailableCollateralToLiquidate(
    collateralReserve,
    vars.debtReserveCache,
    vars.actualDebtToLiquidate,
    vars.userCollateralBalance,
    vars.liquidationBonus,
    IPool(params.pool).getAssetPrice(params.collateralAsset),
    IPool(params.pool).getAssetPrice(params.debtAsset),
    IPool(params.pool).factory().liquidationProtocolFeePercentage()
);
```
For example, if the previous liquidity index is 1.2, and now it's 1.4(if we update the state), and the user has 100shares of collateral reserve, we calculate the available amount as 120 Collateral instead of 140 Collateral, which is wrong.

- Issue #401 addresses a different issue about how interestRate not get updated with the correct `takenAmount` , which we submitted in #321, which is also  duplicated to a different issue (#228).
 So, #321 should be a duplicate of #401, and this one shouldn't.

**Comment by elhajin** [comment]
escalate 
[comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/403#issuecomment-2395101889)

**Comment by sherlock-admin3** [comment]
> escalate 
> [comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/403#issuecomment-2395101889)
> 

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by obou07** [comment]
escalate 
per [comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/403#issuecomment-2395101889)

**Comment by sherlock-admin3** [comment]
> escalate 
> per [comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/403#issuecomment-2395101889)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
@elhajin you are right that the collateral reserve statе is not updated before calling `_calculateAvailableCollateralToLiquidate()`, which will lead to wrong calculations in the function.

At the beginning of the function, the actual collateral reserve is taken: 

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L104

```solidity
DataTypes.ReserveData storage collateralReserve = reservesData[params.collateralAsset];
```

Before calling `_calculateAvailableCollateralToLiquidate()`, we have a function that validates the liquidation:

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L124-L132

If we have any revert, it should be in `validateLiquidationCall()` function. 

What you say about the index is true, but any user can call `forceUpdateReserve()` and fix the issue:

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/Pool.sol#L160-L172

```solidity
  function forceUpdateReserve(address asset) public {
 DataTypes.ReserveData storage reserve = _reserves[asset];
 DataTypes.ReserveCache memory cache = reserve.cache(_totalSupplies[asset]);
 reserve.updateState(this.getReserveFactor(), cache);
 }
```

This means that the worst-case scenario is that the function is reverting for one block, but once the reserve state is updated, we have no issue.

Planning to accept the escalation that this issue is not dup of #401, and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [obou07](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/403/#issuecomment-2395131061): accepted
