### ISSUE TITLE
A2-security - Protocol exposed to risk of insolvancy, due to not handling bad debt

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#404]
A2-security

Medium

# Protocol exposed to risk of insolvancy, due to not handling bad debt

## Summary
With the new design the repay() function have become permissoned, in contrast to the original aave Implemention (permissionless, anyone can repay a loan of a user). The new changes exposes the protocol to the risk of insolvancy, because bad debt is not (cannot be) handled. leading to a scenario where the last withdrawal will incure the loss. 

## Vulnerability Detail
The codebase have been forked from the AAVE protocol, however the repay funciton have been made permissioned (only position owner can repay loan)
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/Pool.sol#L99-L106

```solidity
  function repay(address asset, uint256 amount, uint256 index, DataTypes.ExtraData memory data) public returns (DataTypes.SharesType memory) {
@>>    return _repay(asset, amount, msg.sender.getPositionId(index), data);
  }

  /// @inheritdoc IPoolSetters
  function repaySimple(address asset, uint256 amount, uint256 index) public returns (DataTypes.SharesType memory) {
@>>    return _repay(asset, amount, msg.sender.getPositionId(index), DataTypes.ExtraData({interestRateData: '', hookData: ''}));
  }
```

as we can see from the implementaion msg.sender is used and only the position owner can repay the position. Those changes have been added to the original codebase.

To put things in perspective, AAVE uses a concept of a safety module. User stake AAVE tokens, and in the event of bad debt, up to 30% of the staked aave tokens are swapped in order to repay the incurred bad debt on behalf of the violator, in order to return the solvancy of the protocol.

The problem in the implementaion now, is if bad debt is incured (Value of debt, becomes more than value of collateral and there is no incentive for liquidations/ violator to repay) There is no way to repay the debt/ close the debt position. This will cause significant insolvancy risk on the protocol, 
The bad debt will continue to gradually accrue interest and grow, but there is no way to close down the debt and repay it.

## Impact
- There is absolutly no way to handle bad debt (repay/socialize), which increase the risk of protocol insolvancy due to the accumulation of bad debt
## Tool used

Manual Review

## Recommendation
We recommend that the protocol makes the repay function permissionless as it is the case in the AAVE code base. This way the protocol will be able to to implement and put systems in place to handle the repayment of bad debt and mitigate protocol insolvancy issues. however please keep in mind ,that repaying a debt of position that borrowed from the `positionManger` directly through the pool, will lead to incorrect balance track in the position manager, and incorrect reward distribution. so you need also to notify the position manager in case of a repay directly through pool. 

Duplicate of #275

**Comment by Flashloan44** [comment]
This should be invalid due to the following reasons:

1. It falsely claims that repay function is permissioned because it focuses on pool contract rather than the NFTPositionManager contract. The repay function below from NFTPositionManager is clearly permissionless. Any user can input valid token ID position in the parameters to pay the related loan position.

````Solidity
File: NFTPositionManager.sol
116:   function repay(AssetOperationParams memory params) external {
117:     if (params.asset == address(0)) revert NFTErrorsLib.ZeroAddressNotAllowed();
118:     IERC20Upgradeable(params.asset).safeTransferFrom(msg.sender, address(this), params.amount);
119:     _repay(params);
120:   }
````
````Solidity
File: NFTPositionManagerSetters.sol
106:   function _repay(AssetOperationParams memory params) internal nonReentrant {
107:     if (params.amount == 0) revert NFTErrorsLib.ZeroValueNotAllowed();
108:     if (params.tokenId == 0) {
109:       if (msg.sender != _ownerOf(_nextId - 1)) revert NFTErrorsLib.NotTokenIdOwner();
110:       params.tokenId = _nextId - 1;
111:     }
112: 
113:     Position memory userPosition = _positions[params.tokenId];
114: 
115:     IPool pool = IPool(userPosition.pool);
116:     IERC20 asset = IERC20(params.asset);
117: 
118:     asset.forceApprove(userPosition.pool, params.amount); //@note need to check further for usdt cases
119: 
120:     uint256 previousDebtBalance = pool.getDebt(params.asset, address(this), params.tokenId);
121:     DataTypes.SharesType memory repaid = pool.repay(params.asset, params.amount, params.tokenId, params.data);
122:     uint256 currentDebtBalance = pool.getDebt(params.asset, address(this), params.tokenId);
123: 
124:     if (previousDebtBalance - currentDebtBalance != repaid.assets) {
125:       revert NFTErrorsLib.BalanceMisMatch();
126:     }
127: 
128:     if (currentDebtBalance == 0 && repaid.assets < params.amount) {
129:       asset.safeTransfer(msg.sender, params.amount - repaid.assets);
130:     }
131: 
132:     // update incentives
133:     _handleDebt(address(pool), params.asset, params.tokenId, currentDebtBalance);
134: 
135:     emit NFTEventsLib.Repay(params.asset, params.amount, params.tokenId);
136:   }
137: 
````

2. As per documentation indicated in contest read.me, all loan-related position entries should always start from NFTPositionManager contract. There is no way the user should open position from pool contract because it can cause a lot of issues like reward distribution which can affect him. 

Let say the malicious user force to open position directly to pool contract, to borrow loan and let it become bad debt, that is already another issue which is clearly different from the case submitted by the finder. The finder focuses only in repayment function being permissioned which is clearly not the case.

In other words, the report submitted at most is incomplete and not addressing the root cause. 

Reference link https://github.com/zerolend/zerolend-one

<img width="959" alt="image" src="https://github.com/user-attachments/assets/5240336f-ddcb-4f65-95e3-1c60fe7243f5">

**Comment by nevillehuang** [comment]
Escalate for watson

**Comment by sherlock-admin3** [comment]
> Escalate for watson

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Joshuajee** [comment]
Interesting, I just saw your argument but I still think this issue is valid as borrowing and lending can occur without the NFT Position Manager. Repay only works with the NFT Position manager, if the borrower borrows directly from the pool no one can repay their position.

**Comment by aliX40** [comment]
Literally 1 line under the image u put in the devs stated this:
> The following diagram gives **a rough overview** of the lending pool architecture. For a more in-depth documentation on how the protocol works view the various docs and links below.


Neither in the docs nor the Readme is it stated the users should use NFTPositionManager. Please provide 1 line proving ur claim.

Second of all the fact we mentioned repay function is because of our deep knowledge of other lending protocols like AAVE and why they did. THis is an example + explanation desired  to inform the devs.
The core of the issue we mentioned is that the protocol doesn't hanlde bad debt and for this reason. We are correctly duppicated to issues mentioning the exact same issue.

Even though if we assume it's true that the documentation mentioned that(which is not the case literraly), can you prevent me from taking a loan directly from the pool , and leave it to accrue badDebt? , can you repay this loan when it becomes badDebt through NFTPositionManager as you said ??

**Comment by Flashloan44** [comment]
Just want to reiterate what I've said since you ask me about taking loan directly from the pool.

"Let say the malicious user force to open position directly to pool contract, to borrow loan and let it become bad debt, that is already another issue which is clearly different from the case submitted by the finder. The finder focuses only in repayment function being permissioned which is clearly not the case."

The report finding is at best is incomplete. The attack vector above has never been mentioned in the original report. Let alone showing proof if that scenario is possible (from supply to borrow to repayment scenario). It focuses only on repayment they believed is totally permissioned which is clearly not and complete disregard of normal repayment flow process as presented by protocol diagram. In other words, it doesn't cover the whole picture. 

Therefore, I believe that this finding is incomplete and not able to show the complete flow of attack from the original report because of wrong focus of the real issue.

**Comment by aliX40** [comment]
Hi friend,
We have proved all ur arguments are not valid.
U changed ur mind now from, not valid to incomplete. I think u are not being fair and u are not providing any reasonable arguments.

There is enough arguments from our side and the report is clear enough. Will leave the lead judge @cvetanovv  to decide and will try to answer the requests of the lead judge if he have any.

**Comment by 0xjuaan** [comment]
My team submitted this issue, so we benefit from this dupe being invalidated, but its clear that they mentioned "leading to a scenario where the last withdrawal will incure the loss". Also as a side note it makes more sense to make this the primary issue since it shows the devs why the implementation is different to AAVE and how to fix it.

**Comment by cvetanovv** [comment]
I agree with @aliX40 and @0xjuaan comments.

The issue shows an important concern about handling bad debt and how it differs from AAVE's implementation.

The core of the issue highlighted here is valid, focusing on the protocol's inability to handle bad debt efficiently, leading to a potential risk of insolvency.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
High
Duplicate of #275

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [nevillehuang](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/404/#issuecomment-2394917405): rejected
