### ISSUE TITLE
trachev - Interest rates can be artificially lowered when liquidations occur

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#408]
trachev

Medium

# Interest rates can be artificially lowered when liquidations occur

### Summary

When liquidations occur two calls to `updateInterestRates` are made. After the two interest rates are executed, debt tokens are transferred from the liquidator and collateral tokens are transferred to the liquidator. The issue is that a malicious liquidator can take advantage of that order of events by liquidating a position that has an asset that is used both for collateral and for debt. As a result, the malicious liquidator will artificially decrease the interest rate in an asset's reserve, harming all of the reserve's suppliers.

This will happen as if the debt token and the collateral tokens are the same, the second interest update, performed in `_burnCollateralTokens`, will override the first interest rate update. As a result, the liquidity added in the [first call to `updateInterestRates`](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L168) will not be considered when the interest rates are eventually calculated.

For example, 1 ETH of the collateral is liquidated from a position and the liquidator is going to have to pay 1 ETH for the debt. [`_repayDebtTokens`](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L161) is called, which reduces the total debt in `vars.debtReserveCache`, after that `updateInterestRates` is called. The interest rate is calculated by taking into account `the total asset balance of the pool + the liquidity added - the liquidity taken` (taken from [here](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/periphery/ir/DefaultReserveInterestRateStrategy.sol#L112)). The `_liquidityAdded` parameter of `updateInterestRates` is set to `vars.actualDebtToLiquidate`, because the debt tokens are yet to be transferred by the liquidator.
Now, `_burnCollateralTokens` is called, which also calls `updateInterestRates`. This time, `updateInterestRates` needs to update the interest rates based on the collateral transferred to the liquidator, thus `vars.actualCollateralToLiquidate` is set as the `_liquidityTaken` parameter of `updateInterestRates`.
However, if the debt and collateral tokens are the same, the second `updateInterestRates` will override the `_liquidityAdded` of the first `updateInterestRates`. This happens as the debt tokens are still not transferred to the pool and in the `the total asset balance of the pool + the liquidity added - the liquidity taken` calculation the asset balance of the pool will remain the same, but the liquidity added will be 0, instead of `vars.actualDebtToLiquidate`. As a result, interest rates will be lower than they should be, causing a loss of funds for all suppliers of a reserve.

### Root Cause

- In [`executeLiquidationCall`](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L94) the order of interest updates and token transfers allow for interest rates to be maliciously manipulated.

### Attack Path

1. User liquidates 1 ETH of collateral, by paying 1 ETH of debt.
2. Overall the new interest rate updated, after the entire function has been implemented, should be calculated based on the `ETH.balanceOf(pool) + repaid_debt  - withdrawn_collateral => ETH.balanceOf(pool) + 1 ETH - 1 ETH`, however as the second call to update the interest rate will override the first it will be: `ETH.balanceOf(pool) + 0 - 1 ETH`
3. As a result, interest rates are lower than they should be and reserve suppliers accrue less interest than they should.

### Impact

Reserve suppliers accrue less interest than they are entitled to.

### Mitigation

Consider, transferring the debt tokens from the liquidator to the pool before calling `_burnCollateralTokens`.

**Comment by trachevgeorgi** [comment]
Escalate
This issue has been incorrectly duplicated to #228. The root cause of #228 is '_burnCollateralTokens does not account for liquidation fees when withdrawing collateral'. I have submitted an issue that has been correctly set as a duplicate of #228: #260. As we can see they both have the same root cause and the same mitigations.
On the other hand, #408 is not related to #228, except that it is in the same part of the code, which should not be a reason for duplication. As we can see in #408 the root cause of the issue is 'the order of interest updates and token transfers'. This essentially causes the second interest rate update to override the first one.
Furthermore, even if #228 was fixed with the recommended mitigation #408 would still be a valid issue as the second interest rate update will continue to override the first one.
Essentially, #408 has a completely different root cause and mitigation than #228, thus they are not related and #408 should be updated to a Medium with no duplicates.

**Comment by sherlock-admin3** [comment]
> Escalate
> This issue has been incorrectly duplicated to #228. The root cause of #228 is '_burnCollateralTokens does not account for liquidation fees when withdrawing collateral'. I have submitted an issue that has been correctly set as a duplicate of #228: #260. As we can see they both have the same root cause and the same mitigations.
> On the other hand, #408 is not related to #228, except that it is in the same part of the code, which should not be a reason for duplication. As we can see in #408 the root cause of the issue is 'the order of interest updates and token transfers'. This essentially causes the second interest rate update to override the first one.
> Furthermore, even if #228 was fixed with the recommended mitigation #408 would still be a valid issue as the second interest rate update will continue to override the first one.
> Essentially, #408 has a completely different root cause and mitigation than #228, thus they are not related and #408 should be updated to a Medium with no duplicates.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Honour-d-dev** [comment]
This issue is indeed not a duplicate of #228 and should instead be invalid.

The conditions required for this to happen is not reasonable, as it requires the borrower to borrow in the same token as collateral
e.g. if the ltv of ETH is 0.75, then a borrower would supply 1ETH in collateral to borrow 0.75ETH back from pool + accruing interest???. 
When they can simply just withdraw their collateral

**Comment by trachevgeorgi** [comment]
> This issue is indeed not a duplicate of #228 and should instead be invalid.
> 
> The conditions required for this to happen is not reasonable, as it requires the borrower to borrow in the same token as collateral e.g. if the ltv of ETH is 0.75, then a borrower would supply 1ETH in collateral to borrow 0.75ETH back from pool + accruing interest???. When they can simply just withdraw their collateral

The attack will be performed intentionally in order to manipulate the interest rates. Depending on the interest rate strategy used the attacker can unfairly decrease or increase the interest rate. Furthermore, as they will be liquidating themselves they will not be losing any of their collateral.

**Comment by cvetanovv** [comment]
I will quote the root cause of the issue: 

"The issue is that a malicious liquidator can take advantage of that order of events by liquidating a position that **has an asset that is used both for collateral and for debt**."

No user will leave, for example, 1000 USDC as collateral to take 800 USDC. There is no logic in that. 

Even if the malicious liquidator did the whole thing, not only is this grief attack not profitable for him, but someone can front-run him and steal his collateral. No one would risk that. 

I'm planning to accept the escalation that this issue is not a duplicate of #228 but will invalidate the issue.

**Comment by trachevgeorgi** [comment]
> I will quote the root cause of the issue:
> 
> "The issue is that a malicious liquidator can take advantage of that order of events by liquidating a position that **has an asset that is used both for collateral and for debt**."
> 
> No user will leave, for example, 1000 USDC as collateral to take 800 USDC. There is no logic in that.
> 
> Even if the malicious liquidator did the whole thing, not only is this grief attack not profitable for him, but someone can front-run him and steal his collateral. No one would risk that.
> 
> I'm planning to accept the escalation that this issue is not a duplicate of #228 but will invalidate the issue.

As I explained above the position will be created by the malicious actor in order to manipulate the interest rates. The attack can be profitable for the attacker as, depending on the interest rate strategy used, they can unfairly increase the interest rate. Furthermore, as they will be liquidating themselves they wouldn't experience a loss of funds.

**Comment by cvetanovv** [comment]
@trachevgeorgi

If they increase the interest rate, won't everyone benefit?

What if a user or liquidation bot front-runs him and steals his collateral?

**Comment by trachevgeorgi** [comment]
> @trachevgeorgi
> 
> If they increase the interest rate, won't everyone benefit?
> 
> What if a user or liquidation bot front-runs him and steals his collateral?

I agree that there is a risk for their collateral to be stolen, however it can also be avoided.
On your first point, if they were to decrease the interest rate everyone will be harmed, which I believe is even more impactful.

**Comment by Honour-d-dev** [comment]
>Furthermore, as they will be liquidating themselves they wouldn't experience a loss of funds.

This is false, there's a protocol fee on liquidations, plus there's no guarantee they won't get front-run

**Comment by cvetanovv** [comment]
> > Furthermore, as they will be liquidating themselves they wouldn't experience a loss of funds.
> 
> This is false, there's a protocol fee on liquidations, plus there's no guarantee they won't get front-run

Yes, I agree. The risk of losing his collateral is very high + he needs to pay fees. No one would do it for a grief attack, which gains nothing. 

My previous decision remains: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/408#issuecomment-2419072676

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [trachevgeorgi](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/408/#issuecomment-2391150682): accepted
