### ISSUE TITLE
000000 - Full liquidations are possible at an earlier point due to off by one error

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-new-scope-judging#42]
000000

Medium

# Full liquidations are possible at an earlier point due to off by one error

## Summary
Full liquidations are possible at an earlier point due to off by one error
## Vulnerability Detail
Upon liquidations, we call `LiquidationLogic::_calculateDebt()`, there we have this line:
```solidity
    uint256 closeFactor = healthFactor > CLOSE_FACTOR_HF_THRESHOLD ? DEFAULT_LIQUIDATION_CLOSE_FACTOR : MAX_LIQUIDATION_CLOSE_FACTOR;
```
If the health factor is above 0.95e18, we can liquidate half of the user's debt (5000 BIPS). If equal or below, we can liquidate the whole user's debt (10_000 BIPS). However, that is incorrect. We should be able to liquidate the whole debt only if the helath factor is below 0.95e18, not if they are equal. This is also seen in the natspec of the function:

>@dev If the Health Factor is below CLOSE_FACTOR_HF_THRESHOLD, the close factor is increased to MAX_LIQUIDATION_CLOSE_FACTOR

This is an extremely important function in the code so such an error could be very detrimental.
## Impact
Full liquidations are possible at an earlier point due to off by one error
## Code Snippet
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L259-L273
## Tool used

Manual Review

## Recommendation
```diff
-uint256 closeFactor = healthFactor > CLOSE_FACTOR_HF_THRESHOLD ? DEFAULT_LIQUIDATION_CLOSE_FACTOR : MAX_LIQUIDATION_CLOSE_FACTOR;
+uint256 closeFactor = healthFactor >= CLOSE_FACTOR_HF_THRESHOLD ? DEFAULT_LIQUIDATION_CLOSE_FACTOR : MAX_LIQUIDATION_CLOSE_FACTOR;
```

**Comment by Joshuajee** [comment]
Escalate 
While the above code might be a replica of AAVE implementation, the current docs of this protocol say otherwise
You can check it here https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L68. The documentation here is the highest source of truth and it states that only HF below 0.95 is eligible for full liquidation.

**Comment by sherlock-admin3** [comment]
> Escalate 
> While the above code might be a replica of AAVE implementation, the current docs of this protocol say otherwise
> You can check it here https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L68. The documentation here is the highest source of truth and it states that only HF below 0.95 is eligible for full liquidation.
> 
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by samuraii77** [comment]
It is an assumption that there is nothing wrong with the Aave codebase regarding this, not an actual provable fact. Who is to say that I have not submitted it on Immunefi?

**Comment by cvetanovv** [comment]
> Escalate While the above code might be a replica of AAVE implementation, the current docs of this protocol say otherwise You can check it here https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L68. The documentation here is the highest source of truth and it states that only HF below 0.95 is eligible for full liquidation.

The code is 1 to 1 with AAVE. Even the comments. You can check here: https://github.com/aave/aave-v3-core/blob/master/contracts/protocol/libraries/logic/LiquidationLogic.sol#L63-L68

In the Readme they have written that they use AAVE as the basis. Because of this, we can say that this is a design decision.

Planning to reject the escalation and leave the issue as is.

**Comment by samuraii77** [comment]
@cvetanovv, this can not be a design decision. The comments clearly state (both in Aave and in Zerolend) what the expected design is and that design is not followed as explained in my report. Just because it is copied from Aave does not make the code correct, we can clearly see it is incorrect from the comments. Furthermore, my previous comment still stands as an argument.

However, if you classify copying incorrect code and pasting it into your protocol as a design decision, I agree with your decision.

**Comment by cvetanovv** [comment]
The implementation is the same as in AAVE. There is no way to be a Medium severity for one point difference.

This is no more than low severity.

Regarding your previous comment, if you can prove that you were paid a bug bounty by AAVE for medium severity, I will check internally to see if it can also be medium severity because the protocol uses AAVE as the basis. 

My decision to reject the escalation remains.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [joshuajee](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/42/#issuecomment-2390816324): rejected
