### ISSUE TITLE
Nihavent - Claiming dust buildup in `NFTRewardsDistributor` will remove unclaimed rewards for all users

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#435]
Nihavent

Medium

# Claiming dust buildup in `NFTRewardsDistributor` will remove unclaimed rewards for all users

### Summary

Dust builds up on the `NFTRewardsDistributor` contract. The impact is lower for tokens with higher precision, however as meantioned in the readme, USDC is in scope which has 6 decimals of precision. This leads to a non-trivial buildup of dust across the possible `assetHash` that may be rewarded. This dust buildup is supposed to be claimable through the `sweep()` function, however this function transfers all assets off the contract including unclaimed rewards, causing user `getReward()` calls to revert.

### Root Cause

Precision loss occurs on the two lines indicated of [`notifyRewardAmount`](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/positions/NFTRewardsDistributor.sol#L125-L137) below. Some amount of `reward` is divided by the `rewardDuration` and the result is rounded down, leaving the dust amount to accrue on the contract. This value will become significant across all possible `_assetHash` as these are unique for a given pool/asset/isDebt combination, with each requiring their own reward amount.

```javascript
  function notifyRewardAmount(uint256 reward, address pool, address asset, bool isDebt) external onlyRole(REWARDS_ALLOCATOR_ROLE) {
    rewardsToken.transferFrom(msg.sender, address(this), reward);

    bytes32 _assetHash = assetHash(pool, asset, isDebt);
    _updateReward(0, _assetHash);

    if (block.timestamp >= periodFinish[_assetHash]) {
@>    rewardRate[_assetHash] = reward.div(rewardsDuration);
    } else {
      uint256 remaining = periodFinish[_assetHash].sub(block.timestamp);
      uint256 leftover = remaining.mul(rewardRate[_assetHash]);
@>    rewardRate[_assetHash] = reward.add(leftover).div(rewardsDuration);
    }
```

Over time, the admin would like to sweep this dust off the contract, so they call [`NFTPositionManager::sweep()`](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/positions/NFTPositionManager.sol#L131-L139), which transfers all assets off the contract including **all* unclaimed rewards across all pools/assets/users.

```javascript
  function sweep(address token) external onlyRole(DEFAULT_ADMIN_ROLE) {
    if (token == address(0)) {
      uint256 bal = address(this).balance;
      payable(msg.sender).transfer(bal);
    } else {
      IERC20Upgradeable erc20 = IERC20Upgradeable(token);
      erc20.safeTransfer(msg.sender, erc20.balanceOf(address(this)));
    }
  }
```

### Internal pre-conditions

- Admin sweeps dust buildup of any `rewardToken`

### Attack Path

- After some time, significant dust has built up on the `NFTRewardsDistributor` contract, and the admin would like to sweep it.
- Admin calls `sweep()`
- All pending rewards including ongoing reward distributions and previously completed but unclaimed reward distributions are removed, along with the dust.
- Any users who had pending rewards will not be able to claim them, as `getReward()` will revert.

### Impact

- The impact is variable as it depends on when how many unclaimed rewards existed when `sweep()` was called. 
- There may never be a fair time to call `sweep()`:
  - To have no impact on stakers, it must be called when no ongoing rewards are being distributed across all pools/assets/isDebt combinations, and all pending rewards have been claimed by all users. 
  - It seems like this condition may never be met and therefore the admin is left with a choice to forfeit the dust or remove unclaimed rewards from users.

### PoC

Paste the following test in /test/forge/core/positions/. It shows an admin attempting to sweep dust off the contract, but inadvertently removing Alice's rewards

```javascript
// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.19;

import {NFTPostionManagerTest} from './NFTPositionManagerTest.t.sol';
import {DataTypes} from 'contracts/core/pool/configuration/DataTypes.sol';
import {INFTPositionManager} from 'contracts/interfaces/INFTPositionManager.sol';
import {NFTErrorsLib} from 'contracts/interfaces/errors/NFTErrorsLib.sol';
import {console2} from 'forge-std/src/Test.sol';

contract Audit_ClaimingDustRemovesPendingRewards is NFTPostionManagerTest {

  function test_POC_ClaimingDustRemovesPendingRewards() external {
    testShouldSupplyAlice();
    uint256 repayAmount = 10 ether;
    uint256 borrowAmount = 20 ether;
    DataTypes.ExtraData memory data = DataTypes.ExtraData(bytes(''), bytes(''));
    INFTPositionManager.AssetOperationParams memory params =
      INFTPositionManager.AssetOperationParams(address(tokenA), alice, borrowAmount, 1, data);

    vm.startPrank(alice);
    nftPositionManager.borrow(params);
    assertEq(tokenA.balanceOf(address(pool)), 30 ether, 'Pool Revert');
    assertEq(tokenA.balanceOf(alice), 70 ether, 'Alice Revert');
    vm.stopPrank();

    // Setup reward distribution
    address rewarder = makeAddr('Rewarder');
    vm.startPrank(owner);
    nftPositionManager.grantRole(bytes32(keccak256('REWARDS_ALLOCATOR_ROLE')), rewarder);
    vm.stopPrank();

    // Rewarder allocates
    uint256 rewardAmount = 10e18;
    _mintAndApprove(rewarder, tokenA, rewardAmount, address(nftPositionManager)); 
    vm.startPrank(rewarder);
    nftPositionManager.notifyRewardAmount(rewardAmount, address(pool), address(tokenA), true);
    vm.stopPrank();

    // Time passes
    vm.warp(block.timestamp + 7 days);

    // Halfway through Alice's reward distribution, admin sweeps
    vm.startPrank(owner);
    nftPositionManager.sweep(address(tokenA));
    vm.stopPrank();

    vm.warp(block.timestamp + 7 days);

    // Alice claims
    vm.startPrank(alice);
    bytes32 assetHash = keccak256(abi.encode(address(pool), address(tokenA), true));
    vm.expectRevert('ERC20: transfer amount exceeds balance'); // Alice can't claim as their rewards were swept
    nftPositionManager.getReward(1, assetHash);
    vm.stopPrank();

  }
}
```

### Mitigation

- Keep internal accounting of the accumulated dust as a separate balance from the `rewardToken.balanceOf()`
- Adjust the `sweep()` function to only send the accumulated dust, not all reward tokens.

Duplicate of #64

**Comment by Nihavent** [comment]
Escalate

This report is not a dupe of https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/64 which identifies precision loss in the `NFTPositionManager`. 

This report should be valid. It describes a bug in the implementation of `sweep()` function, specifically dust cannot be swept without taking pending rewards from users. 
Although `sweep()` will be called by admin, there is never a fair time to call this as there will nearly always be pending rewards (either currently in a rewardPeriod, or post-rewardPeriod with unclaimed rewards). 

With the current implementation the admin has the following choices:
- Never call `sweep()` which breaks contract functionality of being able to sweep dust.
- Call `sweep()` and remove all pending rewards for all users, which results in loss of user rewards and permanently broken contract accounting
- Wait for all rewards to be claimed across all asset hash before calling `sweep()`, which will likely never occur

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This report is not a dupe of https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/64 which identifies precision loss in the `NFTPositionManager`. 
> 
> This report should be valid. It describes a bug in the implementation of `sweep()` function, specifically dust cannot be swept without taking pending rewards from users. 
> Although `sweep()` will be called by admin, there is never a fair time to call this as there will nearly always be pending rewards (either currently in a rewardPeriod, or post-rewardPeriod with unclaimed rewards). 
> 
> With the current implementation the admin has the following choices:
> - Never call `sweep()` which breaks contract functionality of being able to sweep dust.
> - Call `sweep()` and remove all pending rewards for all users, which results in loss of user rewards and permanently broken contract accounting
> - Wait for all rewards to be claimed across all asset hash before calling `sweep()`, which will likely never occur

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by iamnmt** [comment]
#116 is a dup

**Comment by Nihavent** [comment]
This is also similar to https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/221

**Comment by Honour-d-dev** [comment]
I believe the sponsor confirmed that zero is the only reward token and zero is a standard erc20 with 18 decimals so the dust here is negligible if it even exists

**Comment by Nihavent** [comment]
> I believe the sponsor confirmed that zero is the only reward token and zero is a standard erc20 with 18 decimals so the dust here is negligible if it even exists

The issue is, when `sweep()` is called it claims all assets on the contract (not just the dust) and irretrievably breaks contract accounting going forward. 

If what you're saying is the protocol would never call `sweep()` to avoid this issue, I would respond:

1. The devs intentionally developed a `sweep()` function to claim the dust, if they decide this is unusable then contract functionality is broken
2. In the public discord channel, the sponsor specifically referenced using `sweep()` to clear buildup of funds stuck in the NFTPositionManager contract, thus we have every reason to believe they intend to use this functionality.

<img width="522" alt="Screenshot 2024-10-07 at 17 13 13" src="https://github.com/user-attachments/assets/26c11b78-9823-416b-8b1d-7747c2f0ffeb">

**Comment by cvetanovv** [comment]
This issue is borderline Medium/Low because it falls between the following rules:

>Invalid issue: An admin action can break certain assumptions about the functioning of the code.

>Valid issue: Breaks core contract functionality.

But I think it's more Medium severity because the purpose of `sweep()` is to withdraw only the dust amount from the contract, but currently, it's unusable because it withdraws the whole balance, and this will cause various problems as described in this issue and also in #221 and #116. 

Planning to accept the escalation and duplicate this issue(#435) with #221 and #116. This issue will be the main.

**Comment by 0xSpearmint** [comment]
@cvetanovv This issue is low severity

If the admin never calls `sweep()` the contract will work fine. They only miss out on dust which is not large enough to be medium severity. 

If the admin does call `sweep()` while there are undistributed rewards, then it clearly falls under the sherlock rule:
>An admin action can break certain assumptions about the functioning of the code.

Furthermore it is possible for an admin to call `sweep()` with no issues when there are no undistributed rewards. If we assume users are rational then they will eventually withdraw the rewards from the contract, at that point the admin can call `sweep()` to collect the dust.

**Comment by Nihavent** [comment]
>” If the admin never calls sweep() the contract will work fine. They only miss out on dust which is not large enough to be medium severity.”

As I mentioned [here](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/435#issuecomment-2397912996) we have evidence that the admin intends to call sweep(). 

>” If the admin does call sweep() while there are undistributed rewards, then it clearly falls under the sherlock rule:
>
>An admin action can break certain assumptions about the functioning of the code.”


I don’t believe this rule clearly applies here. Taking all rewards and permanently breaking the contract is a level of impact above ‘Breaking certain assumptions about how the code works’. 

The admin is also trusted to call the function with inputs that will not cause any issues. In this case the input is the reward token and as shown it will always cause issues, therefore they cannot actually call the function to sweep the reward token under Sherlock rules. 

>” Furthermore it is possible for an admin to call sweep() with no issues when there are no undistributed rewards. If we assume users are rational then they will eventually withdraw the rewards from the contract, at that point the admin can call sweep() to collect the dust.”

1. Given there can be thousands of asset hashes (each having n users) this is completely unrealistic to expect there will ever be a state where all rewards are claimed. 

2. Additionally, whilst waiting for rewards to be claimed they could not issue new rewards. 

3. There will also be many positions with ‘dust’ rewards where users claiming will lose value due to gas, ‘rationally’ these users won’t ever claim.

**Comment by Honour-d-dev** [comment]
> > I believe the sponsor confirmed that zero is the only reward token and zero is a standard erc20 with 18 decimals so the dust here is negligible if it even exists
> 
> The issue is, when `sweep()` is called it claims all assets on the contract (not just the dust) and irretrievably breaks contract accounting going forward.
> 
> If what you're saying is the protocol would never call `sweep()` to avoid this issue, I would respond:
> 
> 1. The devs intentionally developed a `sweep()` function to claim the dust, if they decide this is unusable then contract functionality is broken
> 2. In the public discord channel, the sponsor specifically referenced using `sweep()` to clear buildup of funds stuck in the NFTPositionManager contract, thus we have every reason to believe they intend to use this functionality.
> 
> <img alt="Screenshot 2024-10-07 at 17 13 13" width="522" src="https://private-user-images.githubusercontent.com/23513531/374331688-26c11b78-9823-416b-8b1d-7747c2f0ffeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTQyOTcsIm5iZiI6MTcyODY1Mzk5NywicGF0aCI6Ii8yMzUxMzUzMS8zNzQzMzE2ODgtMjZjMTFiNzgtOTgyMy00MTZiLThiMWQtNzc0N2MyZjBmZmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEzMzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZjY0M2Y3ZmU0OTM2N2VmNjBkODM4N2M3ZmI4NTRmMDAyOTE2MjE3ZTU5YmU3OWMzZTIwMTJlYTNjMTVkOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J7YzjcygBLwkDnsz7lQyJ76oF5WzVPaBEVz9_6YRanE">

I'm not assuming the protocol will never call `sweep()` ,however sweep works fine for any other token stuck in the contract, the only exception is the reward token due to the risk of sweeping unclaimed rewards.

My argument is that the reward token (zero) is an 18 decimal token, so there's almost 0 dust accumulated in the `notifyRewardAmount()` as the report claims in the **Root Cause**. So we can safely assume that sweep will not be called on the zero token because the dust build up (if there is any) will not be significant enough

**Comment by Nihavent** [comment]
@Honour-d-dev [this comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/64#issuecomment-2407450517) should address your concern regarding value of dust. 

Given the admin cannot sweep the dust of the rewards token it will build up in the contract over time and result in a loss significant enough to be considered medium severity, especially if USDC were the reward token. 

I also believe that due to the admin wishing to sweep reward token but being unable to due to this bug, the contract functionality is broken, regardless of value.

**Comment by 0xjuaan** [comment]
This is definitely not an issue because if the protocol admin wants to sweep dust, they can sweep the balance and then transfer the rewards back in to the contract in the same transaction. If admins don't do this correctly, it's their fault and not a smart contract vulnerability.

**Comment by Nihavent** [comment]
>”This is definitely not an issue because if the protocol admin wants to sweep dust, they can sweep the balance and then transfer the rewards back in to the contract in the same transaction”

The mitigation you’ve proposed is entirely theoretical. This is because with the current implementation, the amount that needs to be transferred back to the contract cannot be accurately determined. 

The logic required to accurately determine the amount of dust to withhold is an accounting system which separates rewards from dust. This is the same logic that is currently missing from the contract and what was recommended in the mitigation. 

This logic could theoretically be implemented off-chain, but at the time of the contest Watsons were under the impression this would not be the case. 

>”Are there any off-chain mechanisms or off-chain procedures for the protocol (keeper bots, arbitrage bots, etc.)?
>There are liquidation bots that run off-chain to execute liquidations similar to how liquidations work on Aave.”

…

>”If admins don't do this correctly, it's their fault and not a smart contract vulnerability.”

Given that they can’t do this correctly, I don’t believe they can be considered at fault for not doing it.

**Comment by cvetanovv** [comment]
I still think we have broken functionality. 

The only way to avoid having an issue is if the admin doesn't call the function, but this function was implemented for a purpose, and it doesn't work. Because of that, I think it could be of medium severity.

My decision to accept the escalation remains. I will duplicate this issue(#435) with #221 and #116. This issue will be the main.

**Comment by Honour-d-dev** [comment]
@cvetanovv

There is no broken functionality, the sweep function works perfectly and it is not meant to be used for sweeping the reward token.

This issue claims there will be dust build up if low decimal rewards token is used, however we have proven that **zero** is the only reward token and it's standard, so no dust and no need to call sweep on zero.

Sweep works fine for all other tokens that might be stuck in the contract

**Comment by iamnmt** [comment]
@Honour-d-dev 

Unclaimed rewards still build up in the period of no active depositors (i.e. `_totalSupply[_assetHash]` is equal to zero). Please take a look at #116

**Comment by 0xSpearmint** [comment]
@cvetanovv You state the following in your comment.
>The only way to avoid having an issue is if the admin doesn't call the function

But that is not true. Even if the admin calls the function, they can just send the (rewards - dust) amount back into the contract ([see this comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/435#issuecomment-2410948660)).

**Comment by Honour-d-dev** [comment]
> @Honour-d-dev 
> 
> Unclaimed rewards still build up in the period of no active depositors (i.e. `_totalSupply[_assetHash]` is equal to zero). Please take a look at #116 

Then in such case sweeping the reward won't affect any user so no issue there.
Also depositing rewards tokens is an admin functionality, we can expect admin to not distribute rewards if no users

**Comment by cvetanovv** [comment]
> @cvetanovv You state the following in your comment.
> 
> > The only way to avoid having an issue is if the admin doesn't call the function
> 
> But that is not true. Even if the admin calls the function, they can just send the (rewards - dust) amount back into the contract ([see this comment](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/435#issuecomment-2410948660)).

I indeed missed taking this comment into consideration, and that admin has a way to use the function properly: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/435#issuecomment-2410948660

Then the `sweep()` function can work correctly, and this issue falls into the rule "**Admin Input/call validation**":

> Admin could have an incorrect call order. Example: If an Admin forgets to setWithdrawAddress() before calling withdrawAll() This is not a valid issue.

Planning to reject the escalation and leave the issue as is.

**Comment by Nihavent** [comment]
>” I indeed missed taking this comment into consideration, and that admin has a way to use the function properly”

It was explained [here](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/435#issuecomment-2412497412) why the admin does not have a way to use the function properly. 
The functionality to determine the amount to transfer back is missing because the accounting doesn’t separate rewards from dust. 

Without a valid method for the admin to determine the correct value to transfer, the mitigation is entirely theoretical. Note that if they transfer 1 wei less the contract accounting is permenantly broken, if they transfer 1 wei extra then they didn't sweep all dust.

So we can continue to assume the admin doesn’t make input or call order mistakes and they still cannot call `sweep()`.

**Comment by cvetanovv** [comment]
The admin can call the `sweep()` function and then return the rewards back. He is trusted to do this. 

My decision is to reject the escalation.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #64

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Nihavent](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/435/#issuecomment-2391281740): rejected
