### ISSUE TITLE
0xDemon - `BNB` token can't be used if ZEROLEND deploys on `Linea` because chainlink oracle price feed doesn't support it

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-new-scope-judging#460]
0xDemon

High

# `BNB` token can't be used if ZEROLEND deploys on `Linea` because chainlink oracle price feed doesn't support it

### Summary

Based on the contest `README`, 

> **On what chains are the smart contracts going to be deployed?**
Ethereum and Linea primarily. And after that any EVM-compatible network.
> 

and

> **If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [[weird tokens](https://github.com/d-xo/weird-erc20)](https://github.com/d-xo/weird-erc20) you want to integrate?**
> 
> 
> Only standard ERC20 tokens + USDC and BNB are in-scope.
> 

The ZEROLEND protocol assumes that each chain that will be used to deploy the related smart contract has a price feed that supports each asset, but in reality, the chainlink oracle price feed does not support the `BNB` token on the `Linea` chain. This results in the `BNB` token being completely unusable and this breaks the main invariant that the `BNB` token is included in the token whitelist for each chain that will be supported (`Ethereum` mainnet, `Linea`, and `EVM-compatible networks`).

The main reason `BNB` is completely unusable is because when the pool is initiated and the address from the oracle is verified it will revert because the price feed is not available.

### Root Cause

The choice to use chainlink oracle price feed and assume there is a price feed for `BNB` on the `Linea` chain

[PoolGetters.sol:158-163](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/PoolGetters.sol#L158-L163)

### Impact

`BNB` token being completely unusable and this breaks the main invariant that the `BNB` token is included in the token whitelist for each chain that will be supported (`Ethereum` mainnet, `Linea`, and `EVM-compatible networks`)

### PoC

All available chainlink oracle price feed for `Linea` chain can be seen [here](https://data.chain.link/feeds)

### Mitigation

Consider adding another price feed for `BNB` token if protocol still want to support `BNB` token

**Comment by Joshuajee** [comment]
Escalate 

This issue is invalid because it quotes the Readme out of context. 
> If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [weird tokens](https://github.com/d-xo/weird-erc20) you want to integrate?

> Only standard ERC20 tokens + USDC and BNB are in-scope.

The readme states that the protocol will not support weird ERC20 tokens except USDC and BNB. The context of BNB here is that it is a Weird token, the protocol also states that they will be first primarily deployed on Ethereum and Linea, but they will be deployed on another chain. 

Chainlink not having a BNB price feed on Linea is not an issue because a [Custom Price-feed](https://docs.chain.link/data-feeds/selecting-data-feeds#-custom-feeds) can be created for that, also the maximum impact here is that such pools won't exist (because of no available Price-feeds) which is perfectly fine as no fund is lost.

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> This issue is invalid because it quotes the Readme out of context. 
> > If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [weird tokens](https://github.com/d-xo/weird-erc20) you want to integrate?
> 
> > Only standard ERC20 tokens + USDC and BNB are in-scope.
> 
> The readme states that the protocol will not support weird ERC20 tokens except USDC and BNB. The context of BNB here is that it is a Weird token, the protocol also states that they will be first primarily deployed on Ethereum and Linea, but they will be deployed on another chain. 
> 
> Chainlink not having a BNB price feed on Linea is not an issue because a [Custom Price-feed](https://docs.chain.link/data-feeds/selecting-data-feeds#-custom-feeds) can be created for that, also the maximum impact here is that such pools won't exist (because of no available Price-feeds) which is perfectly fine as no fund is lost.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Emanueldlvg** [comment]
Hi @Joshuajee ,
thanks for trying to invalidate this very obvious issue.

> The readme states that the protocol will not support weird ERC20 tokens except USDC and BNB. The context of BNB here is that it is a Weird token, the protocol also states that they will be first primarily deployed on Ethereum and Linea, but they will be deployed on another chain.

First, this issue specifically explains that on `LINEA`, chainlink price feed does not support `BNB` and is not related to other chains. Second, it is clearly written in the `README` that the `BNB` token is an in-scope token.

> Chainlink not having a BNB price feed on Linea is not an issue because a [Custom Price-feed](https://docs.chain.link/data-feeds/selecting-data-feeds#-custom-feeds) can be created for that, also the maximum impact here is that such pools won't exist (because of no available Price-feeds) which is perfectly fine as no fund is lost.

This statement is an assumption that `ZEROLEND` will create a custom price feed because it is not written in the codebase or in the `README` that `ZEROLEND` will use a custom price feed in the `LINEA` chain.
Then based on Sherlock Rules, this issue is clearly a **valid `MEDIUM` issue** because it breaks core contract functionality and breaks the main invariant that `BNB` tokens can be used on the `LINEA` chain.

> Breaks core contract functionality, rendering the contract useless or leading to loss of funds of the affected party larger than 0.01% and 10 USD.

**Comment by elhajin** [comment]
- **INVALID**: Supporting a token doesn't mean we should add it as a reserve on all supported chains.
- Additionally, whenever a new pool is created, we should set all supported reserves and their oracles, which is the responsibility of the deployer. Therefore, the deployer may either not set the oracle for BNB on Linea, which will result in a revert.
```js
  function executeInitReserve(
    mapping(address => DataTypes.ReserveData) storage reservesData,
    mapping(uint256 => address) storage reservesList,
    DataTypes.InitReserveParams memory params
  ) external {
    require(Address.isContract(params.asset), PoolErrorsLib.NOT_CONTRACT);
    require(Address.isContract(params.interestRateStrategyAddress), PoolErrorsLib.NOT_CONTRACT);
  >>require(Address.isContract(params.oracle), PoolErrorsLib.NOT_CONTRACT);
  ```
Or they could set a malicious or incorrect oracle for BNB, which doesn't make any sense. Even if that the case, it's still the an owner mistake, and the owner's mistakes do not count.
- So  what is the obvious issue here? It is clear that this is invalid.

**Comment by Emanueldlvg** [comment]
Obvious issue here is that **it is stated that `BNB` is supported on `LINEA` chain but in reality it is not**. Is it not clear enough that this breaks main invariant which is in the contest `README` and the contest `README` is the highest source of truth in the hierarchy?

> INVALID: Supporting a token doesn't mean we should add it as a reserve on all supported chains.

Additionally, this is an assumption that supported tokens (i.e. `BNB`) do not have to be usable on all chains. The main fact is that it is written in the `README` (Sherlock rules) that `BNB` will be supported on the `LINEA` chain but in fact it cannot.
This is not an owner issue, but this is an issue related to breaking the main invariant, if you associate this with the owner issue, it means you do not understand the issue clearly here.

**Comment by Joshuajee** [comment]
@Emanueldlvg can you share where it says it is supported? and mind you custom price-feed is a thing. Here no funds is being lost.

**Comment by Emanueldlvg** [comment]
@Joshuajee `BNB` is the token in scope and `LINEA` is the primary chain where `zerolend` will be deployed, it's all in the contest `README`. You can see above. And how can it be possible if every user wants to use `BNB` they request a custom feed to the aggregator and **`PAY`** for it? it doesn't make sense. Because there is no fact that `zerolend` will provide a custom feed. Tell me which statement that `zerolend` will use a custom feed for `BNB` on the `LINEA` chain. And this is not about fund lost, you can read how the medium issue is classified (I have quoted above), this issue is related to the broken main invariant related to `BNB` not being supported on the `LINEA` chain. I will not repeat unnecessary things and all that has been stated above.

**Comment by cvetanovv** [comment]
In the Readme, it is written which networks the protocol will be deployed on and which tokens will be used:

> On what chains are the smart contracts going to be deployed?
> - Ethereum and **Linea** primarily.

> If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? **Are there any types of weird tokens you want to integrate?**
> Only standard ERC20 tokens + USDC and **BNB are in-scope**

It is clearly written that the protocol will be deployed on the **Linea** network and that from the weird tokens will be used **BNB**. 

In this issue, Watson has correctly described that BNB cannot be used on the Linea network because Chainlink has no such price feed. Because of these points, this issue is valid.

Planning to reject the escalation and leave the issue as is.

**Comment by 0xSpearmint** [comment]
@cvetanovv This issue is invalid.

The root cause of this issue as described by the watson is that there is no chainlink price feed for BNB on Linea. 

The protocol never stated that the oracle **must** be a chainlink oracle, the only requirement by the code is that it adheres to the `IAggregatorV3Interface`. 

Currently PYTH supports a BNB price feed on Linea [proof: search for BNB here](https://www.pyth.network/developers/price-feed-ids?ref=pyth-network.ghost.io)

If a user wanted to deploy a pool with BNB token they can easily create an oracle contract to use the price from PYTH, and use that in their pool.

**Comment by cvetanovv** [comment]
@0xSpearmint You are absolutely right. I hadn't seen this issue from the perspective that the Oracle might not be Chainlink.

The main impact of this issue is that the `BNB` token is unusable because of the missing price feed, but this comment completely invalidates that: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/460#issuecomment-2413487819

Planning to accept the escalation and invalidate the issue.

**Comment by Emanueldlvg** [comment]
@cvetanovv Regarding price feeds in PYTH, the `PoolGetter` contract does not interact or initiate to use the price feeds from PYTH (In other words, the logic in `PoolGetter.sol` cannot use price feeds from PYTH). This remains an issue.
Here is how a contract can use price feeds from PYTH, [here](https://docs.pyth.network/price-feeds/use-real-time-data/evm).
It is clear that the oracle used is chainlink, with the `latestRoundData()` function

**Comment by Emanueldlvg** [comment]
@cvetanovv Additionally, this is the [API](https://api-reference.pyth.network/price-feeds/evm/getPriceNoOlderThan) for using price feeds from PYTH. How can the `getAssetPrice()` function pull price feed data from PYTH using `IAggregatorV3Interface.latestRoundData()` when that function does not exist in PYTH? PYTH price feeds are irrelevant and cannot be used in `PoolGetter.sol` contracts

Edited :
Add `getAssetPrice()` code 
```
function getAssetPrice(address reserve) public view override returns (uint256) {
    (, int256 price,, uint256 updatedAt,) = IAggregatorV3Interface(_reserves[reserve].oracle).latestRoundData();
    require(price > 0, 'Invalid price');
    require(block.timestamp <= updatedAt + 1800, 'Stale Price');
    return uint256(price);
  }
```

**Comment by 0xSpearmint** [comment]
The pool deployer will create an oracle contract that implements the `IAggregatorV3Interface.latestRoundData()` function that will get the price from PYTH and return that price to the pool. 

IAggregatorV3Interface is not only to be implemented by chainlink. it is a standard made by chainlink which has been adopted by other oracle creators, with redstone as an example. it is normal for non-chainlink oracles to be created using this interface which is why it's enforced in the protocol.

**Comment by Emanueldlvg** [comment]
I think this is too far as the concept of Zerolend for normal DeFi users, how can a normal DeFi user deploy his/her own oracle contract and integrate into PYTH.
Then if it is implemented like that, the user must prepare a different and specific oracle contract according to the oracle address that is created by themselves?

**Comment by cvetanovv** [comment]
I agree with @0xSpearmint  comment: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/460#issuecomment-2414402154

The main impact is that `BNB` cannot be used on the Line network, which is invalid, as the comment shows. 

That the user may have no knowledge of integrating Pyth oracle is also not a valid argument.

My decision to accept the escalation and invalidate the issue remains.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [joshuajee](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/460/#issuecomment-2392382795): accepted
