### ISSUE TITLE
000000 - Min/max price is not checked

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#74]
000000

Medium

# Min/max price is not checked

## Summary
Min/max price is not checked
## Vulnerability Detail
Upon getting a price, we do not validate the minimum and max prices from Chainlink:
```solidity
function getAssetPrice(address reserve) public view override returns (uint256) {
    (, int256 price,, uint256 updatedAt,) = IAggregatorV3Interface(_reserves[reserve].oracle).latestRoundData();
    require(price > 0, 'Invalid price');
    require(block.timestamp <= updatedAt + 1800, 'Stale Price');
    return uint256(price);
  }
```
While Chainlink has removed the minimum and max prices for a lot of feeds, they are still available for quite a few. Note that the rules consider this a valid issue:
>Issues related to minAnswer and maxAnswer checks on Chainlink's Price Feeds are considered medium only if the Watson explicitly mentions the price feeds (e.g. USDC/ETH) that require this check.

Here are some feeds with min and max prices on Arbitrum which is a chain that the protocol will be deployed on based on the README (as it's fully EVM-compatible):
ETH / BTC - https://arbiscan.io/address/0x3c8F2d5af2e0F5Ef7C23A08DF6Ad168ece071D4b#readContract
ETH / USD - https://arbiscan.io/address/0x3607e46698d218B3a5Cae44bF381475C0a5e2ca7#readContract
SOL / USD - https://arbiscan.io/address/0x8C4308F7cbD7fB829645853cD188500D7dA8610a#readContract
## Impact
Min/max price is not checked
## Code Snippet
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/PoolGetters.sol#L158-L163
## Tool used

Manual Review

## Recommendation
Implement min and max price checks

**Comment by samuraii77** [comment]
The impact is clear here, reporting prices outside of the minimum and maximum is obviously an issue, especially in a protocol who relies on prices for important actions like liquidations.

**Comment by Emanueldlvg** [comment]
I agree with @samuraii77 ,
This issue has a very clear impact and based on Sherlock rules this is also an issue :

> **Chainlink Price Checks:** Issues related to `minAnswer` and `maxAnswer` checks on Chainlink's Price Feeds are considered medium **only** if the Watson explicitly mentions the price feeds (e.g. USDC/ETH) that require this check.
> 

and based on the contest README, the token used is USDC which can be a `USDC / ETH` pair

> **If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [[weird tokens](https://github.com/d-xo/weird-erc20)](https://github.com/d-xo/weird-erc20) you want to integrate?**
> 
> 
> Only standard ERC20 tokens + USDC and BNB are in-scope.
>

And can someone make an escalation? thanks

**Comment by 0x3b33** [comment]
Escalate 
The above 2 comments describe the arguments pretty well

**Comment by sherlock-admin3** [comment]
> Escalate 
> The above 2 comments describe the arguments pretty well

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation that this issue is valid.

The rules state that an issue is only valid if the correct price feed is mentioned. 

This issue has correctly stated correct price feeds where `min/max` answer is used.

But this does not apply to duplicates where either there is no mention of price feeds at all, or the wrong one is mentioned (USDC/ETH). 

You can check that `USDC/ETH` is not used `min/max` on the following links: https://data.chain.link/feeds, https://etherscan.io/address/0x986b5E1e1755e3C2440e960477f25201B0a8bbD4#readContract, and https://polygonscan.com/address/0xefb7e6be8356cCc6827799B6A7348eE674A80EaE#readContract

Planning to accept the escalation and make this issue a solo Medium.

**Comment by cvetanovv** [comment]
After internal discussion, it was clarified that for this audit, it is taken into account that the protocol will only be deployed on **Ethereum** and **Linea**.

And there are no `min/max` checks on these networks: 

- [ETH/BTC on Ethereum](https://etherscan.io/address/0x7A5dc0C6A59e76B3A65c73224316C110663CEd1B#readContract)
- [ETH/USD on Ethereum](https://etherscan.io/address/0x7d4E742018fb52E48b08BE73d041C18B21de6Fb5#readContract)
- [SOL/USD on Ethereum](https://etherscan.io/address/0xa88757c4D7f75C672a07Ae1Cf8011C4552a275f0#readContract)
- [ETH/USD on Linea](https://lineascan.build/address/0x0635163285C6ef5692167F18b799FB339DF064f8)

This means that the issue is invalid.

Planning to reject the escalation and leave the issue as is.

**Comment by samuraii77** [comment]
@cvetanovv, the README states that the protocol will be deployed on any EVM-compatible chain. Internal discussions are not of importance here especially if they are done after the contest.

**Comment by cvetanovv** [comment]
By internal discussion, I meant to clarify on which networks the protocol will be deployed. 

It has become clear that only Ethereum and Linea are being considered for this audit. This is the reason why the issue is invalid.

My decision to reject the escalation remains.

**Comment by samuraii77** [comment]
@cvetanovv, could you specify where that was mentioned? The README specifies that the protocol will be deployed on all EVM-compatible chains. It was never mentioned that only Ethereum and Linea are considered for the audit as far as I am aware but if you can specify where that was mentioned that is in accordance with the rule below, I will agree with your decision:
>The Sherlock Judge can use public statements up until 24h before the contest ends to override the language in the chosen source of truth.

**Comment by cvetanovv** [comment]
My decision to reject the escalation remains. 

This has been the approach in previous contests. When there are several networks specified on which the protocol will be deployed, and then it is written that "any EVM networks" will be used, then only the specified networks are taken into consideration for the audit, not all of them.

**Comment by samuraii77** [comment]
I still don't agree with the decision. 

Firstly, I have never seen such a situation in a contest before, if I could be pointed to one, that would be great.

The README specifies that this can be deployed on any EVM-compatible chain. As no chain has been explicitly excluded, it is expected for the protocol to work properly on any EVM-compatible chain. Also, Arbitrum (the chain in my report) is one of the most popular chains, it is not some random chain I had to look for to support my claim.

There is currently no rule provided based on which my report is being invalidated while there are many rules based on which my report is valid. Unless such a rule is provided, invalidating the report is completely unfair.

Also, during the contest, I might have provided a price feed that is on Ethereum or Linea that also matches my claim in the report. The reason I didn't is because the README was quite clear regarding this.

"We will deploy on any EVM-compatible chain" does not mean "We won't deploy anywhere", thus the argument is invalid.

**Comment by WangSecurity** [comment]
@cvetanovv is correct above. If the chain is not explicitly mentioned, we cannot be sure the protocol will be deployed there. The README says "any", not every, so it doesn't mean the protocol will be deployed on Arbitrum, but that it might be at some point in the future. Hence, this issue has to remain low as an info/low severity issue. The escalation will be rejected.

**Comment by samuraii77** [comment]
@WangSecurity & @cvetanovv, firstly, let's take a look at the Teller contest [README](https://github.com/sherlock-audit/2024-04-teller-finance?tab=readme-ov-file#q-if-you-are-integrating-tokens-are-you-allowing-only-whitelisted-tokens-to-work-with-the-codebase-or-any-complying-with-the-standard-are-they-assumed-to-have-certain-properties-eg-be-non-reentrant-are-there-any-types-of-weird-tokens-you-want-to-integrate):
>We are allowing any standard token that would be compatible with Uniswap V3 to work with our codebase

As seen, the word "any" was used there as well. Now, let's take a look at some of the issues in that contest:
[Fee-on-transfer tokens](https://github.com/sherlock-audit/2024-04-teller-finance-judging/issues/122)
[Uniswap pools with extremely high sqrtPriceX96](https://github.com/sherlock-audit/2024-04-teller-finance-judging/issues/243)
[Tokens that dont revert on failure](https://github.com/sherlock-audit/2024-04-teller-finance-judging/issues/50)

We can clearly see that the word "any" there was interpreted correctly. Of course, historical decisions are not a source of truth but this is the exact same scenario, thus it is completely unfair to take a different decision under the same circumstances.

Furthermore, your understanding of the word "any" is incorrect.

**Comment by WangSecurity** [comment]
Firstly, as you've said historical decisions are not sources of truth and it's irrelevant here.
Secondly, it's not the exact scenario, because it's about tokens and it has at least some specifics ("compatible with Uniswap V3").
Finally, if you want an example from a different contest, take a look at this [issue from Sentiment](https://github.com/sherlock-audit/2024-08-sentiment-v2-judging/issues/550).

The decision remains, reject the escalation and leave the issue as it is.

**Comment by samuraii77** [comment]
It's the absolute same scenario, we have some specifics here as well (EVM-compatible chain, not any chain) As a matter of fact, the current README is a lot more specific than the Teller one - EVM compatible chains follow a set of rules that allow them to be __compatible__ while tokens in Uniswap can be any token including such that don't strictly follow the ERC20 standard. 

Your decision is completely against the rules. If you believe the rules are not good enough, consider changing them after the running contests are over. Up until then, the rules must be followed and not twisted to suit your narrative.

**Comment by WangSecurity** [comment]
> It's the absolute same scenario, we have some specifics here as well

It's a different scenario as said above.

> Your decision is completely against the rules. If you believe the rules are not good enough, consider changing them after the running contests are over. Up until then, the rules must be followed and not twisted to suit your narrative

I'm not twisting any rules, and my decision doesn't go against any of the rules. The decision remains, reject the escalation and leave the issue as it is.

**Comment by samuraii77** [comment]
>It's a different scenario as said above.

Yes, it's a different one, this README is a lot more specific. If you have an argument regarding that, bring it up. Your initial argument was completely invalid as explained in my comment above.

>Im not twisting any rules

You used the word "any" so you are not specifying any rule that you are not twisting, thus you are twisting every rule (according to your understanding of the word "any", hope you see how crazy and wrong your invalidation reason is, just a joke so don't take it as an insult). 


> my decision doesn't go against any of the rules.

Yes, it does go completely against the rules. The README is clear about it and according to the rules, this is a Medium. Cite me the exact rule that says that if the README is not absolutely specific regarding chains (even though the current README is still very specific and mentions the type of chains a deployment is planned on), we will ignore it. If you show me such a rule, I will agree with you. If not, then you are going against the rules.

I would like an argument to every one of my arguments brought up and not cherrypicking, that way we reach an honest consensus we can both agree on, thank you.

**Comment by WangSecurity** [comment]
> Yes, it's a different one, this README is a lot more specific. If you have an argument regarding that, bring it up. Your initial argument was completely invalid as explained in my comment above.

It doesn’t change the fact that historical decisions are not sources of truth.

> You used the word "any" so you are not specifying any rule that you are not twisting, thus you are twisting every rule (according to your understanding of the word "any", hope you see how crazy and wrong your invalidation reason is, just a joke so don't take it as an insult).

I see what you mean, indeed you caught me here, but still it doesn’t change the fact that I don’t twist the rules here.

> Yes, it does go completely against the rules. The README is clear about it and according to the rules, this is a Medium. Cite me the exact rule that says that if the README is not absolutely specific regarding chains (even though the current README is still very specific and mentions the type of chains a deployment is planned on), we will ignore it. If you show me such a rule, I will agree with you. If not, then you are going against the rules.

Here’s the rule saying that if the README is not specific enough, the rules apply:
> If the protocol team provides no specific information, the default rules apply (judging guidelines).

There are no rules saying that in this situation Arbitrum should be in scope. Moreover, the Watson didn’t mention any rule that is violated here. Lastly, saying “any EVM-compatible chain” is not specific enough.

Result:
Invalid
Has duplicates

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/74/#issuecomment-2390975092): rejected
